/* TuxBlox - Linux Compatibility Layer for the Roblox Engine
 * Copyright (C) 2026 TuxBlox Developers
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/* compat/webkitgtk/bundle/host/errorpage_template.h
 *
 * GENERATED FILE -- do not edit by hand. Edit host/errorpage.html and run:
 *
 *     python3 compat/webkitgtk/bundle/host/generate-errorpage-template.py
 *
 * The error page, compiled in so the binary carries it and nothing ships
 * beside it. errorpage.c fills the {{SLOTS}} and drops the IF_URL block when
 * there is no URL to offer.
 */
#ifndef WV2L_HOST_ERRORPAGE_TEMPLATE_H
#define WV2L_HOST_ERRORPAGE_TEMPLATE_H

static const char errorpage_template[] =
    "<!--\n"
    "TuxBlox - Linux Compatibility Layer for the Roblox Engine\n"
    "Copyright (C) 2026 TuxBlox Developers\n"
    "\n"
    "This program is free software: you can redistribute it and/or modify\n"
    "it under the terms of the GNU General Public License as published by\n"
    "the Free Software Foundation, either version 3 of the License, or\n"
    "(at your option) any later version.\n"
    "\n"
    "This program is distributed in the hope that it will be useful,\n"
    "but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
    "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n"
    "GNU General Public License for more details.\n"
    "\n"
    "You should have received a copy of the GNU General Public License\n"
    "along with this program. If not, see <https://www.gnu.org/licenses/>.\n"
    "-->\n"
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>{{HEADING}}</title>\n"
    "<style>\n"
    "@font-face {\n"
    "    font-family: 'Inter';\n"
    "    font-style: normal;\n"
    "    font-weight: 400;\n"
    "    src: url(data:font/woff2;base64,{{FONT_INTER_400}}) format('woff2');\n"
    "}\n"
    "@font-face {\n"
    "    font-family: 'Inter';\n"
    "    font-style: normal;\n"
    "    font-weight: 600;\n"
    "    src: url(data:font/woff2;base64,{{FONT_INTER_600}}) format('woff2');\n"
    "}\n"
    "@font-face {\n"
    "    font-family: 'Montserrat';\n"
    "    font-style: normal;\n"
    "    font-weight: 700;\n"
    "    src: url(data:font/woff2;base64,{{FONT_MONTSERRAT_700}}) format('woff2');\n"
    "}\n"
    "\n"
    "/* Colours, radii and button geometry are the ones in\n"
    "   static.tuxblox.net/styles/style.css, so this reads as part of the site\n"
    "   rather than as something Wine put on screen. */\n"
    ":root {\n"
    "    --bg: #0a0c11;\n"
    "    --bg-soft: #13171f;\n"
    "    --divider: #232833;\n"
    "    --brand: #38bdf8;\n"
    "    --brand-soft: rgba(56, 189, 248, .12);\n"
    "    --text-1: #e9ecf1;\n"
    "    --text-2: #98a1b0;\n"
    "    --text-3: #79828f;\n"
    "    --btn-bg: #0273ae;\n"
    "    --btn-hover: #01608f;\n"
    "    --sans: 'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif;\n"
    "    --display: 'Montserrat', 'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif;\n"
    "    color-scheme: dark;\n"
    "}\n"
    "\n"
    "* { box-sizing: border-box; }\n"
    "html, body { height: 100%; }\n"
    "\n"
    "body {\n"
    "    margin: 0;\n"
    "    background: var(--bg);\n"
    "    color: var(--text-1);\n"
    "    font-family: var(--sans);\n"
    "    line-height: 1.6;\n"
    "    letter-spacing: -.011em;\n"
    "    -webkit-font-smoothing: antialiased;\n"
    "    display: flex;\n"
    "    align-items: center;\n"
    "    justify-content: center;\n"
    "    padding: 40px 24px;\n"
    "}\n"
    "\n"
    "main { width: 100%; max-width: 460px; }\n"
    "\n"
    ".mark { margin-bottom: 22px; }\n"
    "\n"
    ".kicker {\n"
    "    margin: 0 0 10px;\n"
    "    font-size: 11px;\n"
    "    font-weight: 600;\n"
    "    letter-spacing: .1em;\n"
    "    text-transform: uppercase;\n"
    "    color: var(--text-3);\n"
    "    font-variant-numeric: tabular-nums;\n"
    "}\n"
    "\n"
    "h1 {\n"
    "    margin: 0;\n"
    "    font-family: var(--display);\n"
    "    font-size: 27px;\n"
    "    font-weight: 700;\n"
    "    line-height: 1.25;\n"
    "    letter-spacing: -.02em;\n"
    "    text-wrap: balance;\n"
    "}\n"
    "\n"
    "p.body {\n"
    "    margin: 14px 0 0;\n"
    "    font-size: 15.5px;\n"
    "    line-height: 1.7;\n"
    "    color: var(--text-2);\n"
    "}\n"
    "p.body b { color: var(--text-1); font-weight: 600; }\n"
    "\n"
    ".url {\n"
    "    margin: 20px 0 0;\n"
    "    padding: 10px 12px;\n"
    "    background: var(--bg-soft);\n"
    "    border: 1px solid var(--divider);\n"
    "    border-radius: 4px;\n"
    "    font-size: 12.5px;\n"
    "    color: var(--text-3);\n"
    "    letter-spacing: 0;\n"
    "    font-variant-numeric: tabular-nums;\n"
    "    overflow-x: auto;\n"
    "    white-space: nowrap;\n"
    "}\n"
    "\n"
    ".actions { margin-top: 26px; }\n"
    "\n"
    "a.btn {\n"
    "    display: inline-flex;\n"
    "    align-items: center;\n"
    "    justify-content: center;\n"
    "    gap: 8px;\n"
    "    height: 40px;\n"
    "    padding: 0 20px;\n"
    "    border: 1px solid transparent;\n"
    "    border-radius: 4px;\n"
    "    background: var(--btn-bg);\n"
    "    color: #fff;\n"
    "    font: 600 14px var(--sans);\n"
    "    text-decoration: none;\n"
    "    transition: background-color .25s ease;\n"
    "}\n"
    "a.btn:hover, a.btn:focus-visible { background: var(--btn-hover); }\n"
    "a.btn svg { width: 15px; height: 15px; }\n"
    "\n"
    "details {\n"
    "    margin-top: 24px;\n"
    "    border-top: 1px solid var(--divider);\n"
    "    padding-top: 16px;\n"
    "}\n"
    "\n"
    "summary {\n"
    "    cursor: pointer;\n"
    "    list-style: none;\n"
    "    font-size: 13px;\n"
    "    color: var(--text-3);\n"
    "    display: inline-flex;\n"
    "    align-items: center;\n"
    "    gap: 8px;\n"
    "}\n"
    "summary::-webkit-details-marker { display: none; }\n"
    "summary::before {\n"
    "    content: \"\";\n"
    "    width: 0;\n"
    "    height: 0;\n"
    "    border-left: 5px solid currentColor;\n"
    "    border-top: 4px solid transparent;\n"
    "    border-bottom: 4px solid transparent;\n"
    "}\n"
    "details[open] summary::before { transform: rotate(90deg); }\n"
    "summary:hover { color: var(--text-2); }\n"
    "\n"
    "dl {\n"
    "    margin: 14px 0 0;\n"
    "    display: grid;\n"
    "    grid-template-columns: max-content minmax(0, 1fr);\n"
    "    gap: 7px 16px;\n"
    "    font-size: 12.5px;\n"
    "    font-variant-numeric: tabular-nums;\n"
    "}\n"
    "dt { color: var(--text-3); font-weight: 600; }\n"
    "dd { margin: 0; color: var(--text-2); overflow-wrap: anywhere; }\n"
    "\n"
    ":focus-visible { outline: 2px solid var(--brand); outline-offset: 2px; border-radius: 2px; }\n"
    "::selection { background: var(--brand-soft); color: var(--text-1); }\n"
    "\n"
    "@media (prefers-reduced-motion: reduce) {\n"
    "    * { transition: none !important; }\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<main>\n"
    "    <!-- The TuxBlox mark from static.tuxblox.net/images/svg/tuxblox.svg. -->\n"
    "    <div class=\"mark\">\n"
    "        <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"-10 -10 220 220\" width=\"52\" height=\"52\" aria-hidden=\"true\">\n"
    "            <defs>\n"
    "                <linearGradient id=\"tbBlue\" x1=\"0%\" y1=\"0%\" x2=\"0%\" y2=\"100%\">\n"
    "                    <stop offset=\"0%\" stop-color=\"#009fff\"/>\n"
    "                    <stop offset=\"100%\" stop-color=\"#0ca2f6\"/>\n"
    "                </linearGradient>\n"
    "                <linearGradient id=\"tbAmber\" x1=\"0%\" y1=\"0%\" x2=\"0%\" y2=\"100%\">\n"
    "                    <stop offset=\"0%\" stop-color=\"#ffa01a\"/>\n"
    "                    <stop offset=\"100%\" stop-color=\"#fba31b\"/>\n"
    "                </linearGradient>\n"
    "            </defs>\n"
    "            <g transform=\"rotate(14 100 100)\">\n"
    "                <path d=\"M20 20 180 20 180 90 124 90 124 76 76 76 76 90 20 90Z\"\n"
    "                      fill=\"url(#tbBlue)\" stroke=\"url(#tbBlue)\" stroke-width=\"8\"\n"
    "                      stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n"
    "                <path d=\"M20 180 180 180 180 110 124 110 124 124 76 124 76 110 20 110Z\"\n"
    "                      fill=\"url(#tbAmber)\" stroke=\"url(#tbAmber)\" stroke-width=\"8\"\n"
    "                      stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n"
    "            </g>\n"
    "        </svg>\n"
    "    </div>\n"
    "\n"
    "    <p class=\"kicker\">{{KICKER}}</p>\n"
    "    <h1>{{HEADING}}</h1>\n"
    "    <p class=\"body\">{{BODY}}</p>\n"
    "\n"
    "<!--IF_URL-->\n"
    "    <p class=\"url\">{{URL}}</p>\n"
    "    <div class=\"actions\">\n"
    "        <a class=\"btn\" href=\"{{URL}}\">\n"
    "            <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 16 16\" fill=\"none\"\n"
    "                 stroke=\"currentColor\" stroke-width=\"1.7\" stroke-linecap=\"round\"\n"
    "                 stroke-linejoin=\"round\" aria-hidden=\"true\">\n"
    "                <path d=\"M13.7 7.2A5.8 5.8 0 1 1 12 3.4\"/>\n"
    "                <path d=\"M13.4 1.6v3.6H9.8\"/>\n"
    "            </svg>\n"
    "            Try again\n"
    "        </a>\n"
    "    </div>\n"
    "<!--END_URL-->\n"
    "\n"
    "    <details>\n"
    "        <summary>Technical details</summary>\n"
    "        <dl>{{DETAILS}}</dl>\n"
    "    </details>\n"
    "</main>\n"
    "</body>\n"
    "</html>\n"
    "\n";

#endif /* WV2L_HOST_ERRORPAGE_TEMPLATE_H */
