@ extern -arch=win32 Wow64Transition __wine_syscall_dispatcher
@ stub -syscall=0x110a NtBindCompositionSurface
@ stub -syscall=0x110b NtCloseCompositionInputSink
@ stub -syscall NtCompositionInputThread
@ stub -syscall=0x110c NtCompositionSetDropTarget
@ stub -syscall=0x110d NtCompositorNotifyExitWindows
@ stub -syscall NtCompositorNotifyForegroundChanged
@ stub -syscall NtCompositorUpdateLastInputTime
@ stub -syscall=0x110e NtConfigureInputSpace
@ stub -syscall=0x110f NtConfirmCompositionSurfaceIndependentFlipEntry
@ stub -syscall=0x1110 NtCreateCompositionInputSink
@ stub -syscall=0x1111 NtCreateCompositionSurfaceHandle
@ stub -syscall=0x1112 NtCreateImplicitCompositionInputSink
@ stub -syscall=0x1113 NtDCompositionAddCrossDeviceVisualChild
@ stub -syscall=0x1114 NtDCompositionBeginFrame
@ stub -syscall=0x1115 NtDCompositionBoostCompositorClock
@ stub -syscall=0x1116 NtDCompositionCommitChannel
@ stub -syscall=0x1117 NtDCompositionCommitSynchronizationObject
@ stub -syscall=0x1118 NtDCompositionConfirmFrame
@ stub -syscall=0x1119 NtDCompositionConnectPipe
@ stub -syscall=0x111a NtDCompositionCreateAndBindSharedSection
@ stub -syscall=0x111c NtDCompositionCreateChannel
@ stub -syscall=0x111d NtDCompositionCreateConnection
@ stub -syscall NtDCompositionCreateDwmChannel
@ stub -syscall=0x111e NtDCompositionCreateSharedResourceHandle
@ stub -syscall=0x111f NtDCompositionCreateSynchronizationObject
@ stub -syscall=0x1120 NtDCompositionDestroyChannel
@ stub -syscall=0x1121 NtDCompositionDestroyConnection
@ stub -syscall NtDCompositionDiscardFrame
@ stub -syscall=0x1122 NtDCompositionDuplicateHandleToProcess
@ stub -syscall=0x1123 NtDCompositionDuplicateSwapchainHandleToDwm
@ stub -syscall=0x1124 NtDCompositionEnableMMCSS
@ stub -syscall=0x1125 NtDCompositionGetBatchId
@ stub -syscall=0x1126 NtDCompositionGetChannels
@ stub -syscall=0x1127 NtDCompositionGetConnectionBatch
@ stub -syscall=0x1128 NtDCompositionGetDeletedResources
@ stub -syscall=0x1129 NtDCompositionGetFrameId
@ stub -syscall=0x112a NtDCompositionGetFrameIdFromBatchId
@ stub -syscall=0x112b NtDCompositionGetFrameLegacyTokens
@ stub -syscall=0x112c NtDCompositionGetFrameStatistics
@ stub -syscall=0x112d NtDCompositionGetFrameSurfaceUpdates
@ stub -syscall NtDCompositionGetMaterialProperty
@ stub -syscall=0x112e NtDCompositionGetStatistics
@ stub -syscall=0x112f NtDCompositionGetTargetStatistics
@ stub -syscall=0x1130 NtDCompositionNotifySuperWetInkWork
@ stub -syscall=0x1131 NtDCompositionProcessChannelBatchBuffer
@ stub -syscall NtDCompositionReferenceSharedResourceOnDwmChannel
@ stub -syscall=0x1132 NtDCompositionRegisterThumbnailVisual
@ stub -syscall=0x1133 NtDCompositionRegisterVirtualDesktopVisual
@ stub -syscall=0x1134 NtDCompositionReleaseAllResources
@ stub -syscall=0x1135 NtDCompositionRemoveCrossDeviceVisualChild
@ stub -syscall NtDCompositionRetireFrame
@ stub -syscall=0x1137 NtDCompositionSetBlurredWallpaperSurface
@ stub -syscall=0x1138 NtDCompositionSetChannelCommitCompletionEvent
@ stub -syscall=0x1139 NtDCompositionSetChannelConnectionId
@ stub -syscall=0x113a NtDCompositionSetChildRootVisual
@ stub -syscall=0x113b NtDCompositionSetDebugCounter
@ stub -syscall NtDCompositionSetMaterialProperty
@ stub -syscall NtDCompositionSubmitDWMBatch
@ stub -syscall=0x113c NtDCompositionSuspendAnimations
@ stub -syscall=0x113d NtDCompositionSyncWait
@ stub -syscall=0x113e NtDCompositionSynchronize
@ stub -syscall NtDCompositionTelemetryAnimationScenarioBegin
@ stub -syscall NtDCompositionTelemetryAnimationScenarioReference
@ stub -syscall NtDCompositionTelemetryAnimationScenarioUnreference
@ stub -syscall=0x113f NtDCompositionTelemetrySetApplicationId
@ stub -syscall NtDCompositionTelemetryTouchInteractionBegin
@ stub -syscall NtDCompositionTelemetryTouchInteractionEnd
@ stub -syscall NtDCompositionTelemetryTouchInteractionUpdate
@ stub -syscall=0x1140 NtDCompositionUpdatePointerCapture
@ stub -syscall=0x1141 NtDCompositionWaitForChannel
@ stub -syscall=0x1142 NtDCompositionWaitForCompositorClock
@ stub -syscall=0x1143 NtDesktopCaptureBits
@ stub -syscall=0x1144 NtDuplicateCompositionInputSink
@ stub -syscall=0x1145 NtDxgkCancelPresents
@ stub -syscall=0x1146 NtDxgkCheckSinglePlaneForMultiPlaneOverlaySupport
@ stub -syscall=0x1147 NtDxgkConnectDoorbell
@ stub -syscall=0x1148 NtDxgkCreateDoorbell
@ stub -syscall=0x1149 NtDxgkCreateNativeFence
@ stub -syscall=0x114a NtDxgkCreateTrackedWorkload
@ stub -syscall=0x114c NtDxgkDestroyDoorbell
@ stub -syscall=0x114d NtDxgkDestroyTrackedWorkload
@ stub -syscall=0x114f NtDxgkDispMgrOperation
@ stub -syscall=0x1150 NtDxgkDisplayMuxSwitchExecute
@ stub -syscall=0x1151 NtDxgkDisplayMuxSwitchFinish
@ stub -syscall=0x1152 NtDxgkDisplayMuxSwitchPrepare
@ stub -syscall=0x1153 NtDxgkDisplayPortOperation
@ stub -syscall=0x1154 NtDxgkDuplicateHandle
@ stub -syscall=0x1156 NtDxgkEnumAdapters3
@ stub -syscall=0x1157 NtDxgkEnumProcesses
@ stub -syscall=0x1158 NtDxgkGetAvailableTrackedWorkloadIndex
@ stub -syscall=0x1159 NtDxgkGetNativeFenceLogDetail
@ stub -syscall=0x115a NtDxgkGetProcessList
@ stub -syscall=0x115b NtDxgkGetProperties
@ stub -syscall=0x115c NtDxgkGetTrackedWorkloadStatistics
@ stub -syscall=0x115d NtDxgkIsFeatureEnabled
@ stub -syscall=0x115f NtDxgkNotifyWorkSubmission
@ stub -syscall=0x1160 NtDxgkOpenNativeFenceFromNtHandle
@ stub -syscall=0x1161 NtDxgkOutputDuplPresentToHwQueue
@ stub -syscall=0x1162 NtDxgkPinResources
@ stub -syscall=0x1163 NtDxgkRegisterVailProcess
@ stub -syscall=0x1164 NtDxgkResetTrackedWorkloadStatistics
@ stub -syscall=0x1165 NtDxgkSetProperties
@ stub -syscall=0x1166 NtDxgkSubmitPresentBltToHwQueue
@ stub -syscall=0x1167 NtDxgkSubmitPresentToHwQueue
@ stub -syscall=0x1169 NtDxgkUnpinResources
@ stub -syscall=0x116a NtDxgkUpdateTrackedWorkload
@ stub -syscall=0x116b NtDxgkVailConnect
@ stub -syscall=0x116c NtDxgkVailDisconnect
@ stub -syscall=0x116d NtDxgkVailPromoteCompositionSurface
@ stub -syscall=0x116e NtEnableOneCoreTransformMode
@ stub -syscall=0x116f NtFlipObjectAddContent
@ stub -syscall=0x1170 NtFlipObjectAddPoolBuffer
@ stub -syscall=0x1171 NtFlipObjectConsumerAcquirePresent
@ stub -syscall=0x1172 NtFlipObjectConsumerAdjustUsageReference
@ stub -syscall=0x1173 NtFlipObjectConsumerBeginProcessPresent
@ stub -syscall=0x1174 NtFlipObjectConsumerEndProcessPresent
@ stub -syscall=0x1175 NtFlipObjectConsumerPostMessage
@ stub -syscall=0x1176 NtFlipObjectConsumerQueryBufferInfo
@ stub -syscall=0x1177 NtFlipObjectCreate
@ stub -syscall=0x1178 NtFlipObjectDisconnectEndpoint
@ stub -syscall=0x1179 NtFlipObjectEnablePresentStatisticsType
@ stub -syscall=0x117a NtFlipObjectOpen
@ stub -syscall=0x117b NtFlipObjectPresentCancel
@ stub -syscall=0x117c NtFlipObjectQueryBufferAvailableEvent
@ stub -syscall=0x117d NtFlipObjectQueryEndpointConnected
@ stub -syscall=0x117e NtFlipObjectQueryLostEvent
@ stub -syscall=0x117f NtFlipObjectQueryNextMessageToProducer
@ stub -syscall=0x1180 NtFlipObjectReadNextMessageToProducer
@ stub -syscall=0x1181 NtFlipObjectRemoveContent
@ stub -syscall=0x1182 NtFlipObjectRemovePoolBuffer
@ stub -syscall=0x1183 NtFlipObjectSetContent
@ stub -syscall NtFlipObjectSetMaximumBackchannelQueueDepth
@ stdcall -syscall=0x1184 NtGdiAbortDoc(long)
@ stdcall -syscall=0x1185 NtGdiAbortPath(long)
@ stub -syscall=0x1186 NtGdiAddEmbFontToDC
@ stdcall -syscall=0x10fb NtGdiAddFontMemResourceEx(ptr long ptr long ptr)
@ stdcall -syscall=0x1187 NtGdiAddFontResourceW(wstr long long long long ptr)
@ stub -syscall=0x1188 NtGdiAddInitialFonts
@ stub -syscall=0x1189 NtGdiAddRemoteFontToDC
@ stub -syscall=0x118a NtGdiAddRemoteMMInstanceToDC
@ stdcall -syscall=0x1075 NtGdiAlphaBlend(long long long long long long long long long long long ptr)
@ stdcall -syscall=0x118b NtGdiAngleArc(long long long long long long)
@ stub -syscall=0x118c NtGdiAnyLinkedFonts
@ stdcall -syscall=0x118d NtGdiArcInternal(long long long long long long long long long long)
@ stub -syscall=0x118e NtGdiBRUSHOBJ_DeleteRbrush
@ stub -syscall=0x118f NtGdiBRUSHOBJ_hGetColorTransform
@ stub -syscall=0x1190 NtGdiBRUSHOBJ_pvAllocRbrush
@ stub -syscall=0x1191 NtGdiBRUSHOBJ_pvGetRbrush
@ stub -syscall=0x1192 NtGdiBRUSHOBJ_ulGetBrushColor
@ stub -syscall=0x1193 NtGdiBeginGdiRendering
@ stdcall -syscall=0x10f5 NtGdiBeginPath(long)
@ stdcall -syscall=0x1006 NtGdiBitBlt(long long long long long long long long long long long)
@ stub -syscall=0x1194 NtGdiCLIPOBJ_bEnum
@ stub -syscall=0x1195 NtGdiCLIPOBJ_cEnumStart
@ stub -syscall=0x1196 NtGdiCLIPOBJ_ppoGetPath
@ stdcall -syscall=0x1197 NtGdiCancelDC(long)
@ stub -syscall=0x1198 NtGdiChangeGhostFont
@ stub -syscall=0x1199 NtGdiCheckBitmapBits
@ stub -syscall=0x119a NtGdiClearBitmapAttributes
@ stub -syscall=0x119b NtGdiClearBrushAttributes
@ stdcall -syscall=0x10ec NtGdiCloseFigure(long)
@ stub -syscall=0x119c NtGdiColorCorrectPalette
@ stdcall -syscall=0x102f NtGdiCombineRgn(long long long long)
@ stub -syscall=0x10dd NtGdiCombineTransform
@ stdcall -syscall=0x1083 NtGdiComputeXformCoefficients(long)
@ stub -syscall=0x119d NtGdiConfigureOPMProtectedOutput
@ stub -syscall=0x119e NtGdiConvertMetafileRect
@ stdcall -syscall=0x1066 NtGdiCreateBitmap(long long long long ptr)
@ stub -syscall=0x119f NtGdiCreateBitmapFromDxSurface
@ stub -syscall=0x11a0 NtGdiCreateBitmapFromDxSurface2
@ stdcall -syscall=0x10ac NtGdiCreateClientObj(long)
@ stub -syscall=0x1107 NtGdiCreateColorSpace
@ stub -syscall=0x11a1 NtGdiCreateColorTransform
@ stdcall -syscall=0x1046 NtGdiCreateCompatibleBitmap(long long long)
@ stdcall -syscall=0x104f NtGdiCreateCompatibleDC(long)
@ stdcall -syscall=0x106d NtGdiCreateDIBBrush(ptr long long long long ptr)
@ stdcall -syscall=0x1092 NtGdiCreateDIBSection(long long long ptr long long long long ptr)
@ stdcall -syscall=0x1096 NtGdiCreateDIBitmapInternal(long long long long ptr ptr long long long long long)
@ stdcall -syscall=0x11a2 NtGdiCreateEllipticRgn(long long long long)
@ stdcall -syscall=0x10da NtGdiCreateHalftonePalette(long)
@ stdcall -syscall=0x11a3 NtGdiCreateHatchBrushInternal(long long long)
@ stdcall -syscall=0x11a4 NtGdiCreateMetafileDC(long)
@ stub -syscall=0x11a5 NtGdiCreateOPMProtectedOutput
@ stub -syscall=0x11a6 NtGdiCreateOPMProtectedOutputs
@ stdcall -syscall=0x109e NtGdiCreatePaletteInternal(ptr long)
@ stdcall -syscall=0x10a3 NtGdiCreatePatternBrushInternal(long long long)
@ stdcall -syscall=0x1051 NtGdiCreatePen(long long long long)
@ stdcall -syscall=0x107c NtGdiCreateRectRgn(long long long long)
@ stdcall -syscall=0x11a7 NtGdiCreateRoundRectRgn(long long long long long long)
@ stub -syscall=0x11a8 NtGdiCreateServerMetaFile
@ stub -syscall=0x11a9 NtGdiCreateSessionMappedDIBSection
@ stdcall -syscall=0x10aa NtGdiCreateSolidBrush(long long)
@ stub -syscall=0x11aa NtGdiDDCCIGetCapabilitiesString
@ stub -syscall=0x11ab NtGdiDDCCIGetCapabilitiesStringLength
@ stub -syscall=0x11ac NtGdiDDCCIGetTimingReport
@ stub -syscall=0x11ad NtGdiDDCCIGetVCPFeature
@ stub -syscall=0x11ae NtGdiDDCCISaveCurrentSettings
@ stub -syscall=0x11af NtGdiDDCCISetVCPFeature
@ stub -syscall=0x11b0 NtGdiDdCreateFullscreenSprite
@ stub -syscall=0x11b1 NtGdiDdDDIAbandonSwapChain
@ stdcall -syscall=0x11b2 NtGdiDdDDIAcquireKeyedMutex(ptr)
@ stdcall -syscall=0x11b3 NtGdiDdDDIAcquireKeyedMutex2(ptr)
@ stub -syscall=0x11b4 NtGdiDdDDIAcquireSwapChain
@ stub -syscall=0x11b5 NtGdiDdDDIAddSurfaceToSwapChain
@ stub -syscall=0x11b6 NtGdiDdDDIAdjustFullscreenGamma
@ stub -syscall=0x11b7 NtGdiDdDDICacheHybridQueryValue
@ stub -syscall=0x11b8 NtGdiDdDDIChangeVideoMemoryReservation
@ stub -syscall=0x11b9 NtGdiDdDDICheckExclusiveOwnership
@ stub -syscall=0x11ba NtGdiDdDDICheckMonitorPowerState
@ stub -syscall=0x11bb NtGdiDdDDICheckMultiPlaneOverlaySupport
@ stub -syscall=0x11bc NtGdiDdDDICheckMultiPlaneOverlaySupport2
@ stub -syscall=0x11bd NtGdiDdDDICheckMultiPlaneOverlaySupport3
@ stdcall -syscall=0x11be NtGdiDdDDICheckOcclusion(ptr)
@ stub -syscall=0x11bf NtGdiDdDDICheckSharedResourceAccess
@ stdcall -syscall=0x11c0 NtGdiDdDDICheckVidPnExclusiveOwnership(ptr)
@ stdcall -syscall=0x11c1 NtGdiDdDDICloseAdapter(ptr)
@ stub -syscall=0x11c2 NtGdiDdDDIConfigureSharedResource
@ stdcall -syscall=0x11c3 NtGdiDdDDICreateAllocation(ptr)
@ stdcall -syscall NtGdiDdDDICreateAllocation2(ptr)
@ stub -syscall=0x11c4 NtGdiDdDDICreateBundleObject
@ stub -syscall=0x11c5 NtGdiDdDDICreateContext
@ stub -syscall=0x11c6 NtGdiDdDDICreateContextVirtual
@ stdcall -syscall=0x11c7 NtGdiDdDDICreateDCFromMemory(ptr)
@ stdcall -syscall=0x11c8 NtGdiDdDDICreateDevice(ptr)
@ stub -syscall=0x11c9 NtGdiDdDDICreateHwContext
@ stub -syscall=0x11ca NtGdiDdDDICreateHwQueue
@ stdcall -syscall=0x11cb NtGdiDdDDICreateKeyedMutex(ptr)
@ stdcall -syscall=0x11cc NtGdiDdDDICreateKeyedMutex2(ptr)
@ stub -syscall=0x11cd NtGdiDdDDICreateOutputDupl
@ stub -syscall=0x11ce NtGdiDdDDICreateOverlay
@ stub -syscall=0x11cf NtGdiDdDDICreatePagingQueue
@ stub -syscall=0x11d0 NtGdiDdDDICreateProtectedSession
@ stub -syscall=0x11d1 NtGdiDdDDICreateSwapChain
@ stdcall -syscall=0x11d2 NtGdiDdDDICreateSynchronizationObject(ptr)
@ stdcall -syscall NtGdiDdDDICreateSynchronizationObject2(ptr)
@ stub -syscall=0x11d3 NtGdiDdDDIDDisplayEnum
@ stdcall -syscall=0x11d4 NtGdiDdDDIDestroyAllocation(ptr)
@ stdcall -syscall=0x11d5 NtGdiDdDDIDestroyAllocation2(ptr)
@ stub -syscall=0x11d6 NtGdiDdDDIDestroyContext
@ stdcall -syscall=0x11d7 NtGdiDdDDIDestroyDCFromMemory(ptr)
@ stdcall -syscall=0x11d8 NtGdiDdDDIDestroyDevice(ptr)
@ stub -syscall=0x11d9 NtGdiDdDDIDestroyHwContext
@ stub -syscall=0x11da NtGdiDdDDIDestroyHwQueue
@ stdcall -syscall=0x11db NtGdiDdDDIDestroyKeyedMutex(ptr)
@ stub -syscall=0x11dc NtGdiDdDDIDestroyOutputDupl
@ stub -syscall=0x11dd NtGdiDdDDIDestroyOverlay
@ stub -syscall=0x11de NtGdiDdDDIDestroyPagingQueue
@ stub -syscall=0x11df NtGdiDdDDIDestroyProtectedSession
@ stdcall -syscall=0x11e0 NtGdiDdDDIDestroySynchronizationObject(ptr)
@ stub -syscall=0x11e1 NtGdiDdDDIDispMgrCreate
@ stub -syscall=0x11e2 NtGdiDdDDIDispMgrSourceOperation
@ stub -syscall=0x11e3 NtGdiDdDDIDispMgrTargetOperation
@ stdcall -syscall=0x11e4 NtGdiDdDDIEnumAdapters(ptr)
@ stdcall -syscall=0x11e5 NtGdiDdDDIEnumAdapters2(ptr)
@ stdcall -syscall=0x11e6 NtGdiDdDDIEscape(ptr)
@ stub -syscall=0x11e7 NtGdiDdDDIEvict
@ stub -syscall=0x11e8 NtGdiDdDDIExtractBundleObject
@ stub -syscall=0x11e9 NtGdiDdDDIFlipOverlay
@ stub -syscall=0x11ea NtGdiDdDDIFlushHeapTransitions
@ stub -syscall=0x11eb NtGdiDdDDIFreeGpuVirtualAddress
@ stub -syscall=0x11ec NtGdiDdDDIGetAllocationPriority
@ stub -syscall=0x11ed NtGdiDdDDIGetCachedHybridQueryValue
@ stub -syscall=0x11ee NtGdiDdDDIGetContextInProcessSchedulingPriority
@ stub -syscall=0x11ef NtGdiDdDDIGetContextSchedulingPriority
@ stub -syscall=0x11f0 NtGdiDdDDIGetDWMVerticalBlankEvent
@ stub -syscall=0x11f1 NtGdiDdDDIGetDeviceState
@ stub -syscall=0x11f2 NtGdiDdDDIGetDisplayModeList
@ stub -syscall=0x11f3 NtGdiDdDDIGetMemoryBudgetTarget
@ stub -syscall=0x11f4 NtGdiDdDDIGetMultiPlaneOverlayCaps
@ stub -syscall=0x11f5 NtGdiDdDDIGetMultisampleMethodList
@ stub -syscall=0x11f6 NtGdiDdDDIGetOverlayState
@ stub -syscall=0x11f7 NtGdiDdDDIGetPostCompositionCaps
@ stub -syscall=0x11f8 NtGdiDdDDIGetPresentHistory
@ stub -syscall=0x11f9 NtGdiDdDDIGetPresentQueueEvent
@ stub -syscall=0x11fa NtGdiDdDDIGetProcessDeviceRemovalSupport
@ stub -syscall=0x11fb NtGdiDdDDIGetProcessSchedulingPriorityBand
@ stub -syscall=0x11fc NtGdiDdDDIGetProcessSchedulingPriorityClass
@ stub -syscall=0x11fd NtGdiDdDDIGetResourcePresentPrivateDriverData
@ stub -syscall=0x11fe NtGdiDdDDIGetRuntimeData
@ stub -syscall=0x11ff NtGdiDdDDIGetScanLine
@ stub -syscall=0x1200 NtGdiDdDDIGetSetSwapChainMetadata
@ stub -syscall=0x1201 NtGdiDdDDIGetSharedPrimaryHandle
@ stub -syscall=0x1202 NtGdiDdDDIGetSharedResourceAdapterLuid
@ stub -syscall=0x1203 NtGdiDdDDIGetSharedResourceAdapterLuidFlipManager
@ stub -syscall=0x1204 NtGdiDdDDIGetSwapChainSurfacePhysicalAddress
@ stub -syscall=0x1205 NtGdiDdDDIGetYieldPercentage
@ stub -syscall=0x1206 NtGdiDdDDIInvalidateActiveVidPn
@ stub -syscall=0x1207 NtGdiDdDDIInvalidateCache
@ stub -syscall=0x1208 NtGdiDdDDILock
@ stub -syscall=0x1209 NtGdiDdDDILock2
@ stub -syscall=0x120a NtGdiDdDDIMakeResident
@ stub -syscall=0x120b NtGdiDdDDIMapGpuVirtualAddress
@ stub -syscall=0x120c NtGdiDdDDIMarkDeviceAsError
@ stub -syscall=0x120d NtGdiDdDDINetDispGetNextChunkInfo
@ stub -syscall=0x120e NtGdiDdDDINetDispQueryMiracastDisplayDeviceStatus
@ stub -syscall=0x120f NtGdiDdDDINetDispQueryMiracastDisplayDeviceSupport
@ stub -syscall=0x1210 NtGdiDdDDINetDispStartMiracastDisplayDevice
@ stub -syscall=0x1211 NtGdiDdDDINetDispStopMiracastDisplayDevice
@ stub -syscall=0x1212 NtGdiDdDDIOfferAllocations
@ stdcall -syscall=0x1213 NtGdiDdDDIOpenAdapterFromDeviceName(ptr)
@ stdcall -syscall=0x1214 NtGdiDdDDIOpenAdapterFromHdc(ptr)
@ stdcall -syscall=0x1215 NtGdiDdDDIOpenAdapterFromLuid(ptr)
@ stub -syscall=0x1216 NtGdiDdDDIOpenBundleObjectNtHandleFromName
@ stdcall -syscall=0x1217 NtGdiDdDDIOpenKeyedMutex(ptr)
@ stdcall -syscall=0x1218 NtGdiDdDDIOpenKeyedMutex2(ptr)
@ stdcall -syscall=0x1219 NtGdiDdDDIOpenKeyedMutexFromNtHandle(ptr)
@ stdcall -syscall=0x121a NtGdiDdDDIOpenNtHandleFromName(ptr)
@ stub -syscall=0x121b NtGdiDdDDIOpenProtectedSessionFromNtHandle
@ stdcall -syscall=0x121c NtGdiDdDDIOpenResource(ptr)
@ stdcall -syscall NtGdiDdDDIOpenResource2(ptr)
@ stdcall -syscall=0x121d NtGdiDdDDIOpenResourceFromNtHandle(ptr)
@ stub -syscall=0x121e NtGdiDdDDIOpenSwapChain
@ stdcall -syscall=0x121f NtGdiDdDDIOpenSyncObjectFromNtHandle(ptr)
@ stdcall -syscall=0x1220 NtGdiDdDDIOpenSyncObjectFromNtHandle2(ptr)
@ stdcall -syscall=0x1221 NtGdiDdDDIOpenSyncObjectNtHandleFromName(ptr)
@ stdcall -syscall=0x1222 NtGdiDdDDIOpenSynchronizationObject(ptr)
@ stub -syscall=0x1223 NtGdiDdDDIOutputDuplGetFrameInfo
@ stub -syscall=0x1224 NtGdiDdDDIOutputDuplGetMetaData
@ stub -syscall=0x1225 NtGdiDdDDIOutputDuplGetPointerShapeData
@ stub -syscall=0x1226 NtGdiDdDDIOutputDuplPresent
@ stub -syscall=0x1227 NtGdiDdDDIOutputDuplReleaseFrame
@ stub -syscall=0x1228 NtGdiDdDDIPollDisplayChildren
@ stub -syscall=0x1229 NtGdiDdDDIPresent
@ stub -syscall=0x122a NtGdiDdDDIPresentMultiPlaneOverlay
@ stub -syscall=0x122b NtGdiDdDDIPresentMultiPlaneOverlay2
@ stub -syscall=0x122c NtGdiDdDDIPresentMultiPlaneOverlay3
@ stub -syscall=0x122d NtGdiDdDDIPresentRedirected
@ stdcall -syscall=0x122e NtGdiDdDDIQueryAdapterInfo(ptr)
@ stub -syscall=0x122f NtGdiDdDDIQueryAllocationResidency
@ stub -syscall=0x1230 NtGdiDdDDIQueryClockCalibration
@ stub -syscall=0x1231 NtGdiDdDDIQueryFSEBlock
@ stub -syscall=0x1232 NtGdiDdDDIQueryProcessOfferInfo
@ stub -syscall=0x1233 NtGdiDdDDIQueryProtectedSessionInfoFromNtHandle
@ stub -syscall=0x1234 NtGdiDdDDIQueryProtectedSessionStatus
@ stub -syscall=0x1235 NtGdiDdDDIQueryRemoteVidPnSourceFromGdiDisplayName
@ stdcall -syscall=0x1236 NtGdiDdDDIQueryResourceInfo(ptr)
@ stdcall -syscall=0x1237 NtGdiDdDDIQueryResourceInfoFromNtHandle(ptr)
@ stdcall -syscall=0x1238 NtGdiDdDDIQueryStatistics(ptr)
@ stub -syscall=0x1239 NtGdiDdDDIQueryVidPnExclusiveOwnership
@ stdcall -syscall=0x123a NtGdiDdDDIQueryVideoMemoryInfo(ptr)
@ stub -syscall=0x123b NtGdiDdDDIReclaimAllocations
@ stub -syscall=0x123c NtGdiDdDDIReclaimAllocations2
@ stdcall -syscall=0x123d NtGdiDdDDIReleaseKeyedMutex(ptr)
@ stdcall -syscall=0x123e NtGdiDdDDIReleaseKeyedMutex2(ptr)
@ stub -syscall=0x123f NtGdiDdDDIReleaseProcessVidPnSourceOwners
@ stub -syscall=0x1240 NtGdiDdDDIReleaseSwapChain
@ stub -syscall=0x1241 NtGdiDdDDIRemoveSurfaceFromSwapChain
@ stub -syscall=0x1242 NtGdiDdDDIRender
@ stub -syscall=0x1243 NtGdiDdDDIReserveGpuVirtualAddress
@ stub -syscall=0x1244 NtGdiDdDDISetAllocationPriority
@ stub -syscall=0x1245 NtGdiDdDDISetContextInProcessSchedulingPriority
@ stub -syscall=0x1246 NtGdiDdDDISetContextSchedulingPriority
@ stub -syscall=0x1247 NtGdiDdDDISetDisplayMode
@ stub -syscall=0x1248 NtGdiDdDDISetDodIndirectSwapchain
@ stub -syscall=0x1249 NtGdiDdDDISetFSEBlock
@ stub -syscall=0x124a NtGdiDdDDISetGammaRamp
@ stub -syscall=0x124b NtGdiDdDDISetHwProtectionTeardownRecovery
@ stub -syscall=0x124c NtGdiDdDDISetMemoryBudgetTarget
@ stub -syscall=0x124d NtGdiDdDDISetMonitorColorSpaceTransform
@ stub -syscall=0x124e NtGdiDdDDISetProcessDeviceRemovalSupport
@ stub -syscall=0x124f NtGdiDdDDISetProcessSchedulingPriorityBand
@ stub -syscall=0x1250 NtGdiDdDDISetProcessSchedulingPriorityClass
@ stdcall -syscall=0x1251 NtGdiDdDDISetQueuedLimit(ptr)
@ stub -syscall=0x1252 NtGdiDdDDISetStablePowerState
@ stub -syscall=0x1253 NtGdiDdDDISetStereoEnabled
@ stub -syscall=0x1254 NtGdiDdDDISetSyncRefreshCountWaitTarget
@ stub -syscall=0x1255 NtGdiDdDDISetVidPnSourceHwProtection
@ stdcall -syscall=0x1256 NtGdiDdDDISetVidPnSourceOwner(ptr)
@ stub -syscall=0x1257 NtGdiDdDDISetYieldPercentage
@ stdcall -syscall=0x1258 NtGdiDdDDIShareObjects(long ptr ptr long ptr)
@ stub -syscall=0x1259 NtGdiDdDDISharedPrimaryLockNotification
@ stub -syscall=0x125a NtGdiDdDDISharedPrimaryUnLockNotification
@ stub -syscall=0x125b NtGdiDdDDISignalSynchronizationObject
@ stdcall -syscall=0x125c NtGdiDdDDISignalSynchronizationObjectFromCpu(ptr)
@ stub -syscall=0x125d NtGdiDdDDISignalSynchronizationObjectFromGpu
@ stub -syscall=0x125e NtGdiDdDDISignalSynchronizationObjectFromGpu2
@ stub -syscall=0x125f NtGdiDdDDISubmitCommand
@ stub -syscall=0x1260 NtGdiDdDDISubmitCommandToHwQueue
@ stub -syscall=0x1261 NtGdiDdDDISubmitSignalSyncObjectsToHwQueue
@ stub -syscall=0x1262 NtGdiDdDDISubmitWaitForSyncObjectsToHwQueue
@ stub -syscall=0x1263 NtGdiDdDDITrimProcessCommitment
@ stub -syscall=0x1264 NtGdiDdDDIUnOrderedPresentSwapChain
@ stub -syscall=0x1265 NtGdiDdDDIUnlock
@ stub -syscall=0x1266 NtGdiDdDDIUnlock2
@ stub -syscall=0x1267 NtGdiDdDDIUpdateAllocationProperty
@ stub -syscall=0x1268 NtGdiDdDDIUpdateGpuVirtualAddress
@ stub -syscall=0x1269 NtGdiDdDDIUpdateOverlay
@ stub -syscall=0x126a NtGdiDdDDIWaitForIdle
@ stub -syscall=0x126b NtGdiDdDDIWaitForSynchronizationObject
@ stdcall -syscall=0x126c NtGdiDdDDIWaitForSynchronizationObjectFromCpu(ptr)
@ stub -syscall=0x126d NtGdiDdDDIWaitForSynchronizationObjectFromGpu
@ stub -syscall=0x126e NtGdiDdDDIWaitForVerticalBlankEvent
@ stub -syscall=0x126f NtGdiDdDDIWaitForVerticalBlankEvent2
@ stub -syscall=0x1270 NtGdiDdDestroyFullscreenSprite
@ stub -syscall=0x1271 NtGdiDdNotifyFullscreenSpriteUpdate
@ stub -syscall=0x1272 NtGdiDdQueryVisRgnUniqueness
@ stdcall -syscall=0x107f NtGdiDeleteClientObj(long)
@ stub -syscall=0x1108 NtGdiDeleteColorSpace
@ stub -syscall=0x1273 NtGdiDeleteColorTransform
@ stdcall -syscall=0x1020 NtGdiDeleteObjectApp(long )
@ stdcall -syscall=0x1274 NtGdiDescribePixelFormat(long long long ptr)
@ stub -syscall=0x1275 NtGdiDestroyOPMProtectedOutput
@ stub -syscall=0x1276 NtGdiDestroyPhysicalMonitor
@ stub -syscall=0x1277 NtGdiDisableUMPDSandboxing
@ stub -syscall=0x1278 NtGdiDoBanding
@ stdcall -syscall=0x1042 NtGdiDoPalette(long long long ptr long long)
@ stub -syscall=0x1279 NtGdiDrawEscape
@ stdcall -syscall=0x105c NtGdiDrawStream(long long ptr)
@ stub -syscall=0x127a NtGdiDwmCreatedBitmapRemotingOutput
@ stdcall -syscall=0x127b NtGdiEllipse(long long long long long)
@ stub -syscall=0x127c NtGdiEnableEudc
@ stdcall -syscall=0x127d NtGdiEndDoc(long)
@ stub -syscall=0x127e NtGdiEndGdiRendering
@ stdcall -syscall=0x127f NtGdiEndPage(long)
@ stdcall -syscall=0x10f6 NtGdiEndPath(long)
@ stub -syscall=0x1280 NtGdiEngAlphaBlend
@ stub -syscall=0x1281 NtGdiEngAssociateSurface
@ stub -syscall=0x1282 NtGdiEngBitBlt
@ stub -syscall=0x1283 NtGdiEngCheckAbort
@ stub -syscall=0x1284 NtGdiEngComputeGlyphSet
@ stub -syscall=0x1285 NtGdiEngCopyBits
@ stub -syscall=0x1286 NtGdiEngCreateBitmap
@ stub -syscall=0x1287 NtGdiEngCreateClip
@ stub -syscall=0x1288 NtGdiEngCreateDeviceBitmap
@ stub -syscall=0x1289 NtGdiEngCreateDeviceSurface
@ stub -syscall=0x128a NtGdiEngCreatePalette
@ stub -syscall=0x128b NtGdiEngDeleteClip
@ stub -syscall=0x128c NtGdiEngDeletePalette
@ stub -syscall=0x128d NtGdiEngDeletePath
@ stub -syscall=0x128e NtGdiEngDeleteSurface
@ stub -syscall=0x128f NtGdiEngEraseSurface
@ stub -syscall=0x1290 NtGdiEngFillPath
@ stub -syscall=0x1291 NtGdiEngGradientFill
@ stub -syscall=0x1292 NtGdiEngLineTo
@ stub -syscall=0x1293 NtGdiEngLockSurface
@ stub -syscall=0x1294 NtGdiEngMarkBandingSurface
@ stub -syscall=0x1295 NtGdiEngPaint
@ stub -syscall=0x1296 NtGdiEngPlgBlt
@ stub -syscall=0x1297 NtGdiEngStretchBlt
@ stub -syscall=0x1298 NtGdiEngStretchBltROP
@ stub -syscall=0x1299 NtGdiEngStrokeAndFillPath
@ stub -syscall=0x129a NtGdiEngStrokePath
@ stub -syscall=0x129b NtGdiEngTextOut
@ stub -syscall=0x129c NtGdiEngTransparentBlt
@ stub -syscall=0x129d NtGdiEngUnlockSurface
@ stub -syscall=0x129e NtGdiEnsureDpiDepDefaultGuiFontForPlateau
@ stdcall -syscall=0x129f NtGdiEnumFonts(long long long long wstr long ptr ptr)
@ stub -syscall=0x12a0 NtGdiEnumObjects
@ stdcall -syscall=0x10fc NtGdiEqualRgn(long long)
@ stub -syscall=0x12a1 NtGdiEudcLoadUnloadLink
@ stdcall -syscall=0x1091 NtGdiExcludeClipRect(long long long long long)
@ stdcall -syscall=0x109d NtGdiExtCreatePen(long long long long long long long ptr long long long)
@ stdcall -syscall=0x1082 NtGdiExtCreateRegion(ptr long ptr)
@ stdcall -syscall=0x1101 NtGdiExtEscape(long wstr long long long ptr long ptr)
@ stdcall -syscall=0x12a2 NtGdiExtFloodFill(long long long long long)
@ stdcall -syscall=0x104d NtGdiExtGetObjectW(long long ptr)
@ stdcall -syscall=0x1029 NtGdiExtSelectClipRgn(long long long)
@ stdcall -syscall=0x1033 NtGdiExtTextOutW(long long long long ptr ptr long ptr long)
@ stub -syscall=0x12a3 NtGdiFONTOBJ_cGetAllGlyphHandles
@ stub -syscall=0x12a4 NtGdiFONTOBJ_cGetGlyphs
@ stub -syscall=0x12a5 NtGdiFONTOBJ_pQueryGlyphAttrs
@ stub -syscall=0x12a6 NtGdiFONTOBJ_pfdg
@ stub -syscall=0x12a7 NtGdiFONTOBJ_pifi
@ stub -syscall=0x12a8 NtGdiFONTOBJ_pvTrueTypeFontFile
@ stub -syscall=0x12a9 NtGdiFONTOBJ_pxoGetXform
@ stub -syscall=0x12aa NtGdiFONTOBJ_vGetInfo
@ stdcall -syscall=0x10f7 NtGdiFillPath(long)
@ stdcall -syscall=0x10c1 NtGdiFillRgn(long long long)
@ stdcall -syscall=0x12ab NtGdiFlattenPath(long)
@ stdcall -syscall=0x1010 NtGdiFlush()
@ stdcall -syscall=0x12ac NtGdiFontIsLinked(long)
@ stub -syscall=0x12ad NtGdiForceUFIMapping
@ stdcall -syscall=0x12ae NtGdiFrameRgn(long long long long long)
@ stub -syscall=0x12af NtGdiFullscreenControl
@ stdcall -syscall=0x1061 NtGdiGetAndSetDCDword(long long long ptr)
@ stdcall -syscall=0x103e NtGdiGetAppClipBox(long ptr)
@ stub -syscall NtGdiGetAppliedDeviceGammaRamp
@ stdcall -syscall=0x10cb NtGdiGetBitmapBits(long long ptr)
@ stdcall -syscall=0x10e8 NtGdiGetBitmapDimension(long ptr)
@ stub -syscall=0x12b0 NtGdiGetBitmapDpiScaleValue
@ stdcall -syscall=0x12b1 NtGdiGetBoundsRect(long ptr long)
@ stub -syscall=0x12b2 NtGdiGetCOPPCompatibleOPMInformation
@ stub -syscall=0x12b3 NtGdiGetCertificate
@ stub -syscall=0x12b4 NtGdiGetCertificateByHandle
@ stub -syscall=0x12b5 NtGdiGetCertificateSize
@ stub -syscall=0x12b6 NtGdiGetCertificateSizeByHandle
@ stdcall -syscall=0x12b7 NtGdiGetCharABCWidthsW(long long long ptr long ptr)
@ stub -syscall=0x1007 NtGdiGetCharSet
@ stdcall -syscall=0x10ba NtGdiGetCharWidthInfo(long ptr)
@ stdcall -syscall=0x10b5 NtGdiGetCharWidthW(long long long ptr long ptr)
@ stub -syscall=0x12b8 NtGdiGetCharacterPlacementW
@ stdcall -syscall=0x12b9 NtGdiGetColorAdjustment(long ptr)
@ stub -syscall=0x12ba NtGdiGetColorSpaceforBitmap
@ stub -syscall=0x12bb NtGdiGetCurrentDpiInfo
@ stub -syscall=0x12bc NtGdiGetDCDpiScaleValue
@ stdcall -syscall=0x103a NtGdiGetDCDword(long long ptr)
@ stdcall -syscall=0x1030 NtGdiGetDCObject(long long)
@ stdcall -syscall=0x106c NtGdiGetDCPoint(long long ptr)
@ stub -syscall=0x1093 NtGdiGetDCforBitmap
@ stdcall -syscall=0x107d NtGdiGetDIBitsInternal(long long long long ptr ptr long long long)
@ stdcall -syscall=0x12bd NtGdiGetDeviceCaps(long long)
@ stub -syscall=0x12be NtGdiGetDeviceCapsAll
@ stdcall -syscall NtGdiGetDeviceGammaRamp(long ptr)
@ stub -syscall=0x12bf NtGdiGetDeviceWidth
@ stub -syscall=0x12c0 NtGdiGetDhpdev
@ stub -syscall=0x12c1 NtGdiGetETM
@ stub -syscall=0x12c2 NtGdiGetEmbUFI
@ stub -syscall=0x12c3 NtGdiGetEmbedFonts
@ stub -syscall=0x12c4 NtGdiGetEntry
@ stub -syscall=0x12c5 NtGdiGetEudcTimeStampEx
@ stdcall -syscall=0x10c4 NtGdiGetFontData(long long long ptr long)
@ stdcall -syscall=0x12c6 NtGdiGetFontFileData(long long ptr ptr long)
@ stdcall -syscall=0x12c7 NtGdiGetFontFileInfo(long long ptr long ptr)
@ stub -syscall=0x12c8 NtGdiGetFontResourceInfoInternalW
@ stdcall -syscall=0x12c9 NtGdiGetFontUnicodeRanges(long ptr)
@ stub -syscall NtGdiGetGammaRampCapability
@ stdcall -syscall=0x12ca NtGdiGetGlyphIndicesW(long wstr long ptr long)
@ stub -syscall=0x12cb NtGdiGetGlyphIndicesWInternal
@ stdcall -syscall=0x12cc NtGdiGetGlyphOutline(long long long ptr long ptr ptr long)
@ stdcall -syscall=0x12cd NtGdiGetKerningPairs(long long ptr)
@ stub -syscall=0x12ce NtGdiGetLinkedUFIs
@ stdcall -syscall=0x12cf NtGdiGetMiterLimit(long ptr)
@ stub -syscall=0x12d0 NtGdiGetMonitorID
@ stdcall -syscall=0x106a NtGdiGetNearestColor(long long)
@ stdcall -syscall=0x10b4 NtGdiGetNearestPaletteIndex(long long)
@ stub -syscall=0x12d1 NtGdiGetNumberOfPhysicalMonitors
@ stub -syscall=0x12d2 NtGdiGetOPMInformation
@ stub -syscall=0x12d3 NtGdiGetOPMRandomNumber
@ stub -syscall=0x12d4 NtGdiGetObjectBitmapHandle
@ stdcall -syscall=0x10a5 NtGdiGetOutlineTextMetricsInternalW(long long ptr long)
@ stdcall -syscall=0x12d5 NtGdiGetPath(long ptr ptr long)
@ stub -syscall=0x12d6 NtGdiGetPerBandInfo
@ stub -syscall=0x12d7 NtGdiGetPhysicalMonitorDescription
@ stub -syscall=0x12d8 NtGdiGetPhysicalMonitorFromTarget
@ stub -syscall=0x12d9 NtGdiGetPhysicalMonitors
@ stdcall -syscall=0x10b1 NtGdiGetPixel(long long long)
@ stub -syscall=0x12da NtGdiGetProcessSessionFonts
@ stub -syscall=0x12db NtGdiGetPublicFontTableChangeCookie
@ stdcall -syscall=0x1026 NtGdiGetRandomRgn(long long long)
@ stdcall -syscall=0x10d4 NtGdiGetRasterizerCaps(ptr long)
@ stdcall -syscall=0x12dc NtGdiGetRealizationInfo(long ptr)
@ stdcall -syscall=0x103b NtGdiGetRegionData(long long ptr)
@ stdcall -syscall=0x1060 NtGdiGetRgnBox(long ptr)
@ stub -syscall=0x12dd NtGdiGetServerMetaFileBits
@ stdcall -syscall=0x12de NtGdiGetSpoolMessage(ptr long ptr long)
@ stub -syscall=0x12df NtGdiGetStats
@ stub -syscall=0x12e0 NtGdiGetStringBitmapW
@ stub -syscall=0x12e1 NtGdiGetSuggestedOPMProtectedOutputArraySize
@ stdcall -syscall=0x10fd NtGdiGetSystemPaletteUse(long)
@ stdcall -syscall=0x1048 NtGdiGetTextCharsetInfo(long ptr long)
@ stub -syscall=0x108c NtGdiGetTextExtent
@ stdcall -syscall=0x12e2 NtGdiGetTextExtentExW(long wstr long long ptr ptr ptr long)
@ stdcall -syscall=0x1078 NtGdiGetTextFaceW(long long ptr long)
@ stdcall -syscall=0x106e NtGdiGetTextMetricsW(long ptr long)
@ stdcall -syscall=0x10c9 NtGdiGetTransform(long long ptr)
@ stub -syscall=0x12e3 NtGdiGetUFI
@ stub -syscall=0x12e4 NtGdiGetUFIPathname
@ stub -syscall=0x1063 NtGdiGetWidthTable
@ stdcall -syscall=0x12e5 NtGdiGradientFill(long ptr long ptr long long)
@ stub -syscall=0x12e6 NtGdiHLSurfGetInformation
@ stub -syscall=0x12e7 NtGdiHLSurfSetInformation
@ stub -syscall=0x12e8 NtGdiHT_Get8BPPFormatPalette
@ stub -syscall=0x12e9 NtGdiHT_Get8BPPMaskPalette
@ stdcall -syscall=0x1057 NtGdiHfontCreate(ptr long long long ptr)
@ stdcall -syscall=0x12ea NtGdiIcmBrushInfo(long long ptr ptr ptr ptr ptr long)
@ stub -syscall=0x12eb NtGdiInit
@ stub -syscall=0x12ec NtGdiInit2
@ stdcall -syscall=0x12ed NtGdiInitSpool()
@ stdcall -syscall=0x101e NtGdiIntersectClipRect(long long long long long)
@ stdcall -syscall=0x105f NtGdiInvertRgn(long long)
@ stdcall -syscall=0x103c NtGdiLineTo(long long long)
@ stdcall -syscall=0x12ee NtGdiMakeFontDir(long ptr long wstr long)
@ stub -syscall=0x12ef NtGdiMakeInfoDC
@ stub -syscall=0x12f0 NtGdiMakeObjectUnXferable
@ stub -syscall=0x12f1 NtGdiMakeObjectXferable
@ stdcall -syscall=0x1062 NtGdiMaskBlt(long long long long long long long long long long long long long)
@ stub -syscall=0x12f2 NtGdiMirrorWindowOrg
@ stdcall -syscall=0x10c3 NtGdiModifyWorldTransform(long ptr long)
@ stub -syscall=0x12f3 NtGdiMonoBitmap
@ stdcall -syscall=0x12f4 NtGdiMoveTo(long long long ptr)
@ stdcall -syscall=0x12f5 NtGdiOffsetClipRgn(long long long)
@ stdcall -syscall=0x1076 NtGdiOffsetRgn(long long long)
@ stdcall -syscall=0x10c7 NtGdiOpenDCW(ptr ptr ptr long long ptr ptr ptr)
@ stub -syscall=0x12f6 NtGdiPATHOBJ_bEnum
@ stub -syscall=0x12f7 NtGdiPATHOBJ_bEnumClipLines
@ stub -syscall=0x12f8 NtGdiPATHOBJ_vEnumStart
@ stub -syscall=0x12f9 NtGdiPATHOBJ_vEnumStartClipLines
@ stub -syscall=0x12fa NtGdiPATHOBJ_vGetBounds
@ stdcall -syscall=0x1054 NtGdiPatBlt(long long long long long long)
@ stdcall -syscall=0x12fb NtGdiPathToRegion(long)
@ stdcall -syscall=0x12fc NtGdiPlgBlt(long ptr long long long long long long long long long)
@ stdcall -syscall=0x12fd NtGdiPolyDraw(long ptr ptr long)
@ stub -syscall=0x1068 NtGdiPolyPatBlt
@ stdcall -syscall=0x1043 NtGdiPolyPolyDraw(long ptr ptr long long)
@ stub -syscall=0x12fe NtGdiPolyTextOutW
@ stdcall -syscall=0x12ff NtGdiPtInRegion(long long long)
@ stdcall -syscall=0x1300 NtGdiPtVisible(long long long)
@ stub -syscall=0x10e1 NtGdiQueryFontAssocInfo
@ stub -syscall=0x1301 NtGdiQueryFonts
@ stdcall -syscall=0x10af NtGdiRectInRegion(long ptr)
@ stdcall -syscall=0x102e NtGdiRectVisible(long ptr)
@ stdcall -syscall=0x1088 NtGdiRectangle(long long long long long)
@ stdcall -syscall=0x10fe NtGdiRemoveFontMemResourceEx(long)
@ stdcall -syscall=0x1302 NtGdiRemoveFontResourceW(wstr long long long long ptr)
@ stub -syscall=0x1303 NtGdiRemoveMergeFont
@ stdcall -syscall=0x1304 NtGdiResetDC(long ptr ptr ptr ptr)
@ stdcall -syscall=0x1305 NtGdiResizePalette(long long)
@ stdcall -syscall=0x1035 NtGdiRestoreDC(long long)
@ stdcall -syscall=0x1306 NtGdiRoundRect(long long long long long long long)
@ stub -syscall=0x1307 NtGdiSTROBJ_bEnum
@ stub -syscall=0x1308 NtGdiSTROBJ_bEnumPositionsOnly
@ stub -syscall=0x1309 NtGdiSTROBJ_bGetAdvanceWidths
@ stub -syscall=0x130a NtGdiSTROBJ_dwGetCodePage
@ stub -syscall=0x130b NtGdiSTROBJ_vEnumStart
@ stdcall -syscall=0x1036 NtGdiSaveDC(long)
@ stub -syscall=0x130c NtGdiScaleRgn
@ stub -syscall=0x130d NtGdiScaleValues
@ stdcall -syscall=0x130e NtGdiScaleViewportExtEx(long long long long long ptr)
@ stdcall -syscall=0x130f NtGdiScaleWindowExtEx(long long long long long ptr)
@ stdcall -syscall=0x1009 NtGdiSelectBitmap(long long)
@ stdcall -syscall=0x1310 NtGdiSelectBrush(long long)
@ stdcall -syscall=0x1311 NtGdiSelectClipPath(long long)
@ stdcall -syscall=0x1034 NtGdiSelectFont(long long)
@ stdcall -syscall=0x1312 NtGdiSelectPen(long long)
@ stub -syscall=0x1313 NtGdiSetBitmapAttributes
@ stdcall -syscall=0x10a6 NtGdiSetBitmapBits(long long ptr)
@ stdcall -syscall=0x1102 NtGdiSetBitmapDimension(long long long ptr)
@ stdcall -syscall=0x10e7 NtGdiSetBoundsRect(long ptr long)
@ stub -syscall=0x1314 NtGdiSetBrushAttributes
@ stdcall -syscall=0x109f NtGdiSetBrushOrg(long long long ptr)
@ stdcall -syscall=0x1315 NtGdiSetColorAdjustment(long ptr)
@ stub -syscall=0x1316 NtGdiSetColorSpace
@ stdcall -syscall=0x1025 NtGdiSetDIBitsToDeviceInternal(long long long long long long long long long ptr ptr long long long long long)
@ stdcall -syscall NtGdiSetDeviceGammaRamp(ptr ptr)
@ stub -syscall=0x1103 NtGdiSetFontEnumeration
@ stub -syscall=0x1317 NtGdiSetFontXform
@ stub -syscall=0x1318 NtGdiSetIcmMode
@ stdcall -syscall=0x108e NtGdiSetLayout(long long long)
@ stub -syscall=0x1319 NtGdiSetLinkedUFIs
@ stdcall -syscall=0x131a NtGdiSetMagicColors(long long long)
@ stdcall -syscall=0x10d1 NtGdiSetMetaRgn(long)
@ stdcall -syscall=0x10d2 NtGdiSetMiterLimit(long long ptr)
@ stub -syscall=0x131b NtGdiSetOPMSigningKeyAndSequenceNumbers
@ stub -syscall=0x131c NtGdiSetPUMPDOBJ
@ stdcall -syscall=0x10a1 NtGdiSetPixel(long long long long)
@ stdcall -syscall=0x131d NtGdiSetPixelFormat(long long)
@ stub -syscall NtGdiSetPrivateDeviceGammaRamp
@ stdcall -syscall=0x131e NtGdiSetRectRgn(long long long long long)
@ stub -syscall=0x131f NtGdiSetSizeDevice
@ stdcall -syscall=0x1320 NtGdiSetSystemPaletteUse(long long)
@ stdcall -syscall=0x1321 NtGdiSetTextJustification(long long long)
@ stub -syscall=0x1322 NtGdiSetUMPDSandboxState
@ stdcall -syscall=0x10d3 NtGdiSetVirtualResolution(long long long long long)
@ stdcall -syscall=0x1323 NtGdiStartDoc(long ptr ptr long)
@ stdcall -syscall=0x1324 NtGdiStartPage(long)
@ stdcall -syscall=0x102c NtGdiStretchBlt(long long long long long long long long long long long long)
@ stdcall -syscall=0x1079 NtGdiStretchDIBitsInternal(long long long long long long long long long ptr ptr long long long long long)
@ stdcall -syscall=0x1325 NtGdiStrokeAndFillPath(long)
@ stdcall -syscall=0x1326 NtGdiStrokePath(long)
@ stdcall -syscall=0x1327 NtGdiSwapBuffers(long)
@ stdcall -syscall=0x106b NtGdiTransformPoints(long ptr ptr long long)
@ stdcall -syscall=0x1328 NtGdiTransparentBlt(long long long long long long long long long long long)
@ stub -syscall=0x1329 NtGdiUMPDEngFreeUserMem
@ stub -syscall=0x132a NtGdiUnloadPrinterDriver
@ stub -syscall=0x132b NtGdiUnmapMemFont
@ stdcall -syscall=0x1086 NtGdiUnrealizeObject(long)
@ stdcall -syscall=0x132c NtGdiUpdateColors(long)
@ stub -syscall=0x132d NtGdiUpdateTransform
@ stub -syscall=0x132e NtGdiWaitForTextReady
@ stdcall -syscall=0x132f NtGdiWidenPath(long)
@ stub -syscall=0x1330 NtGdiXFORMOBJ_bApplyXform
@ stub -syscall=0x1331 NtGdiXFORMOBJ_iGetXform
@ stub -syscall=0x1332 NtGdiXLATEOBJ_cGetPalette
@ stub -syscall=0x1333 NtGdiXLATEOBJ_hGetColorTransform
@ stub -syscall=0x1335 NtGdiXLATEOBJ_iXlate
@ stub -syscall=0x1336 NtHWCursorUpdatePointer
@ stub -syscall=0x1337 NtInputSpaceRegionFromPoint
@ stub -syscall=0x1338 NtIsOneCoreTransformMode
@ stub -syscall=0x1339 NtKSTInitialize
@ stub -syscall=0x133a NtKSTWait
@ stub -syscall=0x133b NtMITAccessibilityTimerNotification
@ stub -syscall=0x133c NtMITActivateInputProcessing
@ stub -syscall=0x133d NtMITConfigureVirtualTouchpad
@ stub -syscall=0x133e NtMITCoreMsgKOpenConnectionTo
@ stub -syscall=0x133f NtMITDeactivateInputProcessing
@ stub -syscall=0x1340 NtMITDisableMouseIntercept
@ stub -syscall=0x1341 NtMITDispatchCompletion
@ stub -syscall=0x1342 NtMITEnableMouseIntercept
@ stub -syscall=0x1343 NtMITGetCursorUpdateHandle
@ stub -syscall=0x1344 NtMITInitMinuserThread
@ stub -syscall=0x1345 NtMITMinuserSetInputTransformOffset
@ stub -syscall NtMITMinuserWindowCreated
@ stub -syscall=0x1346 NtMITMinuserWindowDestroyed
@ stub -syscall=0x1347 NtMITPostMouseInputMessage
@ stub -syscall=0x1348 NtMITPostThreadEventMessage
@ stub -syscall=0x1349 NtMITPostWindowEventMessage
@ stub -syscall=0x134a NtMITPrepareReceiveInputMessage
@ stub -syscall=0x134b NtMITPrepareSendInputMessage
@ stub -syscall=0x134c NtMITProcessDelegateCapturedPointers
@ stub -syscall NtMITSetForegroundRoutingInfo
@ stub -syscall=0x134d NtMITSetInputCallbacks
@ stub -syscall=0x134e NtMITSetInputDelegationMode
@ stub -syscall=0x134f NtMITSetInputObservationState
@ stub -syscall=0x1350 NtMITSetKeyboardInputRoutingPolicy
@ stub -syscall=0x1351 NtMITSetKeyboardOverriderState
@ stub -syscall=0x1352 NtMITSetLastInputRecipient
@ stub -syscall=0x1353 NtMITSynthesizeKeyboardInput
@ stub -syscall=0x1354 NtMITSynthesizeMouseInput
@ stub -syscall=0x1355 NtMITSynthesizeTouchInput
@ stub -syscall=0x1356 NtMITUninitMinuserThread
@ stub -syscall=0x1357 NtMITUpdateInputGlobals
@ stub -syscall=0x1358 NtMapVisualRelativePoints
@ stub -syscall=0x1359 NtMinGetInputTransform
@ stub -syscall=0x135a NtMinInteropCoreMessagingWithInput
@ stub -syscall=0x135b NtMinQPeekForInput
@ stub -syscall=0x135c NtMinQSuspendInputProcessing
@ stub -syscall=0x135d NtMinQUpdateWakeMask
@ stub -syscall=0x135e NtModerncoreBeginLayoutUpdate
@ stub -syscall=0x135f NtModerncoreCreateDCompositionHwndTarget
@ stub -syscall=0x1360 NtModerncoreCreateGDIHwndTarget
@ stub -syscall=0x1361 NtModerncoreDestroyDCompositionHwndTarget
@ stub -syscall=0x1362 NtModerncoreDestroyGDIHwndTarget
@ stub -syscall=0x1363 NtModerncoreEnableResizeLayoutSynchronization
@ stub -syscall=0x1364 NtModerncoreGetNavigationWindowVisual
@ stub -syscall=0x1365 NtModerncoreGetResizeDCompositionSynchronizationObject
@ stub -syscall=0x1366 NtModerncoreGetWindowContentVisual
@ stub -syscall=0x1367 NtModerncoreIdleTimerThread
@ stub -syscall=0x1368 NtModerncoreIsResizeLayoutSynchronizationEnabled
@ stub -syscall=0x1369 NtModerncoreProcessConnect
@ stub -syscall=0x136a NtModerncoreRegisterEnhancedNavigationWindowHandle
@ stub -syscall=0x136b NtModerncoreRegisterNavigationWindowHandle
@ stub -syscall=0x136c NtModerncoreSetNavigationServiceSid
@ stub -syscall=0x136d NtModerncoreUnregisterNavigationWindowHandle
@ stub -syscall=0x136e NtNotifyPresentToCompositionSurface
@ stub -syscall=0x136f NtOpenCompositionSurfaceDirtyRegion
@ stub -syscall=0x1370 NtOpenCompositionSurfaceRealizationInfo
@ stub -syscall=0x1371 NtOpenCompositionSurfaceSectionInfo
@ stub -syscall NtOpenCompositionSurfaceSwapChainHandleInfo
@ stub -syscall=0x1372 NtQueryCompositionInputIsImplicit
@ stub -syscall=0x1373 NtQueryCompositionInputQueueAndTransform
@ stub -syscall=0x1374 NtQueryCompositionInputSink
@ stub -syscall=0x1375 NtQueryCompositionInputSinkLuid
@ stub -syscall=0x1376 NtQueryCompositionInputSinkViewId
@ stub -syscall=0x1377 NtQueryCompositionSurfaceBinding
@ stub -syscall=0x1378 NtQueryCompositionSurfaceFrameRate
@ stub -syscall=0x1379 NtQueryCompositionSurfaceHDRMetaData
@ stub -syscall=0x137a NtQueryCompositionSurfaceRenderingRealization
@ stub -syscall=0x137b NtQueryCompositionSurfaceStatistics
@ stub -syscall=0x137c NtRIMAddInputObserver
@ stub -syscall=0x137d NtRIMAreSiblingDevices
@ stub -syscall=0x137e NtRIMDeviceIoControl
@ stub -syscall=0x137f NtRIMEnableMonitorMappingForDevice
@ stub -syscall=0x1380 NtRIMFreeInputBuffer
@ stub -syscall=0x1381 NtRIMGetDevicePreparsedData
@ stub -syscall=0x1382 NtRIMGetDevicePreparsedDataLockfree
@ stub -syscall=0x1383 NtRIMGetDeviceProperties
@ stub -syscall=0x1384 NtRIMGetDevicePropertiesLockfree
@ stub -syscall=0x1385 NtRIMGetPhysicalDeviceRect
@ stub -syscall=0x1386 NtRIMGetSourceProcessId
@ stub -syscall=0x1387 NtRIMObserveNextInput
@ stub -syscall=0x1388 NtRIMOnAsyncPnpWorkNotification
@ stub -syscall=0x1389 NtRIMOnPnpNotification
@ stub -syscall=0x138a NtRIMOnTimerNotification
@ stub -syscall=0x138b NtRIMQueryDevicePath
@ stub -syscall=0x138c NtRIMReadInput
@ stub -syscall NtRIMRegisterForInput
@ stub -syscall=0x138d NtRIMRegisterForInputEx
@ stub -syscall=0x138e NtRIMRemoveInputObserver
@ stub -syscall=0x138f NtRIMSetDeadzoneRotation
@ stub -syscall=0x1390 NtRIMSetExtendedDeviceProperty
@ stub -syscall=0x1391 NtRIMSetTestModeStatus
@ stub -syscall=0x1392 NtRIMUnregisterForInput
@ stub -syscall=0x1393 NtRIMUpdateInputObserverRegistration
@ stub -syscall=0x1394 NtSetCompositionSurfaceAnalogExclusive
@ stub -syscall=0x1395 NtSetCompositionSurfaceBufferUsage
@ stub -syscall=0x1396 NtSetCompositionSurfaceDirectFlipState
@ stub -syscall=0x1397 NtSetCompositionSurfaceIndependentFlipInfo
@ stub -syscall=0x1398 NtSetCompositionSurfaceStatistics
@ stub -syscall=0x1399 NtSetCursorInputSpace
@ stub -syscall=0x139a NtSetPointerDeviceInputSpace
@ stub -syscall=0x139b NtSetShellCursorState
@ stub -syscall=0x139c NtTokenManagerConfirmOutstandingAnalogToken
@ stub -syscall=0x139d NtTokenManagerCreateCompositionTokenHandle
@ stub -syscall=0x139e NtTokenManagerCreateFlipObjectReturnTokenHandle
@ stub -syscall=0x139f NtTokenManagerCreateFlipObjectTokenHandle
@ stub -syscall=0x13a0 NtTokenManagerGetAnalogExclusiveSurfaceUpdates
@ stub -syscall=0x13a1 NtTokenManagerGetAnalogExclusiveTokenEvent
@ stub -syscall=0x13a2 NtTokenManagerOpenSectionAndEvents
@ stub -syscall=0x13a3 NtTokenManagerThread
@ stub -syscall=0x13a4 NtUnBindCompositionSurface
@ stub -syscall=0x13a5 NtUpdateInputSinkTransforms
@ stub -syscall=0x13a6 NtUserAcquireIAMKey
@ stub -syscall=0x13a7 NtUserAcquireInteractiveControlBackgroundAccess
@ stdcall -syscall=0x1109 NtUserActivateKeyboardLayout(long long)
@ stdcall -syscall=0x13a8 NtUserAddClipboardFormatListener(long)
@ stub -syscall=0x13a9 NtUserAddVisualIdentifier
@ stub -syscall NtUserAllowForegroundActivation
@ stub -syscall=0x13aa NtUserAllowSetForegroundWindow
@ stdcall -syscall=0x10c0 NtUserAlterWindowStyle(ptr long long)
@ stub -syscall=0x13ab NtUserApplyWindowAction
@ stdcall -syscall=0x13ac NtUserArrangeIconicWindows(long)
@ stdcall -syscall=0x13ad NtUserAssociateInputContext(long long long)
@ stdcall -syscall=0x10d9 NtUserAttachThreadInput(long long long)
@ stub -syscall=0x13ae NtUserAutoPromoteMouseInPointer
@ stub -syscall=0x13af NtUserAutoRotateScreen
@ stdcall -syscall=0x13b0 NtUserBeginDeferWindowPos(long)
@ stub -syscall=0x13b1 NtUserBeginLayoutUpdate
@ stdcall -syscall=0x1015 NtUserBeginPaint(long ptr)
@ stub -syscall=0x10b9 NtUserBitBltSysBmp
@ stub -syscall=0x13b2 NtUserBlockInput
@ stub -syscall=0x13b3 NtUserBroadcastImeShowStatusChange
@ stub -syscall=0x13b4 NtUserBroadcastThemeChangeEvent
@ stdcall -syscall=0x13b5 NtUserBuildHimcList(long long ptr ptr)
@ stdcall -syscall=0x101a NtUserBuildHwndList(long long long long long long ptr ptr)
@ stdcall -syscall=0x10a0 NtUserBuildNameList(long long ptr ptr)
@ stdcall -syscall=0x13b6 NtUserBuildPropList(long long ptr ptr)
@ stub -syscall=0x108f NtUserCalcMenuBar
@ stub -syscall=0x13b7 NtUserCalculatePopupWindowPosition
@ stdcall -syscall NtUserCallHwnd(long long)
@ stub -syscall NtUserCallHwndLock
@ stub -syscall NtUserCallHwndLockSafe
@ stub -syscall NtUserCallHwndOpt
@ stdcall -syscall NtUserCallHwndParam(long ptr long)
@ stub -syscall NtUserCallHwndParamLock
@ stub -syscall NtUserCallHwndParamLockSafe
@ stub -syscall NtUserCallHwndSafe
@ stdcall -syscall=0x1013 NtUserCallMsgFilter(ptr long)
@ stdcall -syscall=0x101c NtUserCallNextHookEx(long long long long)
@ stdcall -syscall NtUserCallNoParam(long)
@ stdcall -syscall NtUserCallOneParam(long long)
@ stdcall -syscall NtUserCallTwoParam(long long long)
@ stub -syscall NtUserCanBrokerForceForeground
@ stub -syscall=0x13b9 NtUserCancelQueueEventCompletionPacket
@ stdcall -syscall=0x1104 NtUserChangeClipboardChain(long long)
@ stdcall -syscall=0x13ba NtUserChangeDisplaySettings(ptr ptr long long ptr)
@ stub -syscall=0x13bb NtUserChangeWindowMessageFilter
@ stub -syscall=0x13bc NtUserChangeWindowMessageFilterEx
@ stub -syscall NtUserCheckAccessForIntegrityLevel
@ stub -syscall=0x13bd NtUserCheckImeShowStatusInThread
@ stdcall -syscall=0x10ef NtUserCheckMenuItem(long long long)
@ stub -syscall=0x13be NtUserCheckProcessForClipboardAccess
@ stub -syscall=0x13bf NtUserCheckProcessSession
@ stub -syscall=0x13c0 NtUserCheckWindowThreadDesktop
@ stdcall -syscall=0x13c1 NtUserChildWindowFromPointEx(long long long long)
@ stub -syscall=0x13c2 NtUserCitSetInfo
@ stub -syscall=0x13c3 NtUserClearForeground
@ stub -syscall=0x13c4 NtUserClearWakeMask
@ stub -syscall=0x13c5 NtUserClearWindowState
@ stdcall -syscall=0x13c6 NtUserClipCursor(ptr)
@ stdcall -syscall=0x10bc NtUserCloseClipboard()
@ stdcall -syscall=0x1099 NtUserCloseDesktop(long)
@ stdcall -syscall=0x10a7 NtUserCloseWindowStation(long)
@ stub -syscall=0x13c7 NtUserCompositionInputSinkLuidFromPoint
@ stub -syscall=0x13c8 NtUserCompositionInputSinkViewInstanceIdFromPoint
@ stub -syscall=0x13c9 NtUserConfigureActivationObject
@ stub -syscall=0x13ca NtUserConfirmResizeCommit
@ stub -syscall=0x10cc NtUserConsoleControl
@ stub -syscall=0x10e9 NtUserConvertMemHandle
@ stdcall -syscall=0x1027 NtUserCopyAcceleratorTable(long ptr long)
@ stdcall -syscall=0x10fa NtUserCountClipboardFormats()
@ stdcall -syscall=0x10de NtUserCreateAcceleratorTable(ptr long)
@ stub -syscall NtUserCreateActivationGroup
@ stub -syscall=0x13cd NtUserCreateActivationObject
@ stub -syscall=0x13ce NtUserCreateBaseWindow
@ stdcall -syscall=0x102d NtUserCreateCaret(long long long long)
@ stub -syscall=0x13cf NtUserCreateDCompositionHwndTarget
@ stdcall -syscall=0x13d0 NtUserCreateDesktopEx(ptr ptr ptr long long long)
@ stub -syscall=0x13d1 NtUserCreateEmptyCursorObject
@ stdcall -syscall=0x13d2 NtUserCreateInputContext(ptr)
@ stub -syscall=0x10d8 NtUserCreateLocalMemHandle
@ stdcall -syscall=0x13d4 NtUserCreateMenu()
@ stub -syscall=0x13d5 NtUserCreatePalmRejectionDelayZone
@ stdcall -syscall=0x13d6 NtUserCreatePopupMenu()
@ stub -syscall=0x13d7 NtUserCreateSyntheticPointerDevice2
@ stub -syscall=0x13d8 NtUserCreateSystemThreads
@ stdcall -syscall=0x106f NtUserCreateWindowEx(long ptr ptr ptr long long long long long long long long ptr long long ptr long)
@ stub -syscall NtUserCreateWindowGroup
@ stdcall -syscall=0x13d9 NtUserCreateWindowStation(ptr long long long long long long)
@ stub -syscall=0x13db NtUserCsDdeUninitialize
@ stub -syscall=0x13dc NtUserCtxDisplayIOCtl
@ stub -syscall=0x13dd NtUserDWP_GetEnabledPopupOffset
@ stub -syscall=0x10f8 NtUserDdeInitialize
@ stub -syscall=0x1077 NtUserDefSetText
@ stub -syscall=0x13de NtUserDeferWindowDpiChanges
@ stdcall -syscall=0x13df NtUserDeferWindowPosAndBand(long long long long long long long long long long)
@ stub -syscall=0x13e0 NtUserDeferredDesktopRotation
@ stub -syscall=0x13e1 NtUserDelegateCapturePointers
@ stub -syscall=0x13e2 NtUserDelegateInput
@ stdcall -syscall=0x10ae NtUserDeleteMenu(long long long)
@ stub -syscall NtUserDeleteWindowGroup
@ stub -syscall=0x13e3 NtUserDeregisterShellHookWindow
@ stdcall -syscall=0x10ea NtUserDestroyAcceleratorTable(long)
@ stub -syscall NtUserDestroyActivationGroup
@ stub -syscall=0x13e4 NtUserDestroyActivationObject
@ stdcall -syscall=0x13e5 NtUserDestroyCaret()
@ stdcall -syscall=0x1094 NtUserDestroyCursor(long long)
@ stub -syscall=0x13e6 NtUserDestroyDCompositionHwndTarget
@ stdcall -syscall=0x13e7 NtUserDestroyInputContext(long)
@ stdcall -syscall=0x10ca NtUserDestroyMenu(long)
@ stub -syscall=0x13e8 NtUserDestroyPalmRejectionDelayZone
@ stdcall -syscall=0x1095 NtUserDestroyWindow(long)
@ stub -syscall NtUserDirectedYield
@ stub -syscall=0x13e9 NtUserDisableImmersiveOwner
@ stub -syscall=0x13ea NtUserDisableProcessWindowFiltering
@ stub -syscall=0x13eb NtUserDisableProcessWindowsGhosting
@ stdcall -syscall=0x13ec NtUserDisableThreadIme(long)
@ stub -syscall=0x13ed NtUserDiscardPointerFrameMessages
@ stdcall -syscall=0x1031 NtUserDispatchMessage(ptr)
@ stdcall -syscall=0x13ee NtUserDisplayConfigGetDeviceInfo(ptr)
@ stub -syscall=0x13ef NtUserDisplayConfigSetDeviceInfo
@ stub -syscall=0x13f0 NtUserDoInitMessagePumpHook
@ stub -syscall=0x13f1 NtUserDoSoundConnect
@ stub -syscall=0x13f2 NtUserDoSoundDisconnect
@ stub -syscall=0x13f3 NtUserDoUninitMessagePumpHook
@ stub -syscall=0x13f4 NtUserDownlevelTouchpad
@ stdcall -syscall=0x13f5 NtUserDragDetect(long long long)
@ stdcall -syscall=0x13f6 NtUserDragObject(long long long long long)
@ stub -syscall=0x13f7 NtUserDrainThreadCoreMessagingCompletions
@ stub -syscall=0x13f8 NtUserDrainThreadCoreMessagingCompletions2
@ stub -syscall=0x13f9 NtUserDrawAnimatedRects
@ stub -syscall=0x13fa NtUserDrawCaption
@ stdcall -syscall=0x13fb NtUserDrawCaptionTemp(long long ptr long long wstr long)
@ stdcall -syscall=0x105a NtUserDrawIconEx(long long long long long long long long long)
@ stdcall -syscall=0x13fc NtUserDrawMenuBar(long)
@ stdcall -syscall=0x13fd NtUserDrawMenuBarTemp(long long ptr long long)
@ stub -syscall=0x13fe NtUserDwmGetRemoteSessionOcclusionEvent
@ stub -syscall=0x13ff NtUserDwmGetRemoteSessionOcclusionState
@ stub -syscall=0x1400 NtUserDwmKernelShutdown
@ stub -syscall=0x1401 NtUserDwmKernelStartup
@ stub -syscall=0x1402 NtUserDwmLockScreenUpdates
@ stub -syscall=0x1403 NtUserDwmValidateWindow
@ stub -syscall=0x1404 NtUserDwmWindowNotificationsEnabled
@ stdcall -syscall=0x10e4 NtUserEmptyClipboard()
@ stub -syscall=0x1405 NtUserEnableChildWindowDpiMessage
@ stub -syscall=0x1406 NtUserEnableIAMAccess
@ stdcall -syscall=0x10bf NtUserEnableMenuItem(long long long)
@ stub -syscall=0x1407 NtUserEnableModernAppWindowKeyboardIntercept
@ stdcall -syscall=0x1408 NtUserEnableMouseInPointer(long)
@ stdcall -syscall=0x1409 NtUserEnableMouseInPointerForThread()
@ stub -syscall=0x140a NtUserEnableMouseInPointerForWindow
@ stub -syscall=0x140b NtUserEnableMouseInputForCursorSuppression
@ stub -syscall=0x140c NtUserEnableNonClientDpiScaling
@ stub -syscall NtUserEnablePerMonitorMenuScaling
@ stub -syscall=0x140d NtUserEnableResizeLayoutSynchronization
@ stdcall -syscall=0x10a9 NtUserEnableScrollBar(long long long)
@ stub -syscall=0x140e NtUserEnableSessionForMMCSS
@ stub -syscall=0x140f NtUserEnableShellWindowManagementBehavior
@ stub -syscall=0x1410 NtUserEnableSoftwareCursorForScreenCapture
@ stub -syscall=0x1412 NtUserEnableTouchPad
@ stdcall -syscall=0x1413 NtUserEnableWindow(long long)
@ stub -syscall=0x1414 NtUserEnableWindowGDIScaledDpiMessage
@ stub -syscall NtUserEnableWindowGroupPolicy
@ stub -syscall=0x1415 NtUserEnableWindowResizeOptimization
@ stub -syscall=0x1416 NtUserEnableWindowShellWindowManagementBehavior
@ stdcall -syscall=0x1023 NtUserEndDeferWindowPosEx(long long)
@ stdcall -syscall=0x1417 NtUserEndMenu()
@ stdcall -syscall=0x1017 NtUserEndPaint(long ptr)
@ stub -syscall=0x1418 NtUserEnsureDpiDepSysMetCacheForPlateau
@ stdcall -syscall=0x141e NtUserEnumClipboardFormats(long)
@ stdcall -syscall=0x10e3 NtUserEnumDisplayDevices(ptr long ptr long)
@ stdcall -syscall=0x1045 NtUserEnumDisplayMonitors(long ptr ptr long)
@ stdcall -syscall=0x10ff NtUserEnumDisplaySettings(ptr long ptr long)
@ stub -syscall=0x141f NtUserEvent
@ stdcall -syscall=0x104b NtUserExcludeUpdateRgn(long long)
@ stub -syscall=0x1081 NtUserFillWindow
@ stdcall -syscall=0x1039 NtUserFindExistingCursorIcon(ptr ptr ptr)
@ stdcall -syscall=0x1067 NtUserFindWindowEx(long long ptr ptr long)
@ stdcall -syscall=0x1420 NtUserFlashWindowEx(ptr)
@ stub -syscall=0x1421 NtUserForceEnableNumpadTranslation
@ stub -syscall=0x1422 NtUserForceWindowToDpiForTest
@ stub -syscall=0x1423 NtUserFrostCrashedWindow
@ stub -syscall=0x1424 NtUserFunctionalizeDisplayConfig
@ stub -syscall=0x1425 NtUserGetActiveProcessesDpis
@ stub -syscall NtUserGetAltTabInfo
@ stdcall -syscall=0x10a4 NtUserGetAncestor(long long)
@ stub -syscall=0x1426 NtUserGetAppImeLevel
@ stdcall -syscall=0x103f NtUserGetAsyncKeyState(long)
@ stdcall -syscall=0x109c NtUserGetAtomName(long ptr)
@ stub -syscall=0x1427 NtUserGetAutoRotationState
@ stub -syscall=0x1428 NtUserGetCIMSSM
@ stub -syscall=0x1040 NtUserGetCPD
@ stdcall -syscall=0x10e0 NtUserGetCaretBlinkTime()
@ stdcall -syscall=0x1429 NtUserGetCaretPos(ptr)
@ stub -syscall=0x142a NtUserGetClassIcoCur
@ stdcall -syscall=0x10ab NtUserGetClassInfoEx(ptr ptr ptr ptr long)
@ stdcall -syscall=0x1074 NtUserGetClassName(long long ptr)
@ stdcall -syscall=0x142b NtUserGetClipCursor(ptr)
@ stub -syscall=0x142c NtUserGetClipboardAccessToken
@ stdcall -syscall=0x10e5 NtUserGetClipboardData(long ptr)
@ stdcall -syscall=0x10d6 NtUserGetClipboardFormatName(long ptr long)
@ stub -syscall=0x142d NtUserGetClipboardMetadata
@ stdcall -syscall=0x10b7 NtUserGetClipboardOwner()
@ stdcall -syscall=0x1050 NtUserGetClipboardSequenceNumber()
@ stdcall -syscall=0x142e NtUserGetClipboardViewer()
@ stub -syscall=0x142f NtUserGetComboBoxInfo
@ stub -syscall=0x1073 NtUserGetControlBrush
@ stub -syscall=0x10d0 NtUserGetControlColor
@ stub -syscall=0x1430 NtUserGetCurrentDpiInfoForWindow
@ stdcall -syscall=0x1431 NtUserGetCurrentInputMessageSource(ptr)
@ stdcall -syscall=0x1432 NtUserGetCursor()
@ stdcall -syscall=0x10df NtUserGetCursorFrameInfo(long long ptr ptr)
@ stdcall -syscall=0x1433 NtUserGetCursorInfo(ptr)
@ stdcall -syscall=0x1434 NtUserGetCursorPos(ptr)
@ stdcall -syscall=0x1008 NtUserGetDC(long)
@ stdcall -syscall=0x108a NtUserGetDCEx(long long long)
@ stub -syscall=0x1435 NtUserGetDCompositionHwndBitmap
@ stub -syscall=0x1436 NtUserGetDManipHookInitFunction
@ stub -syscall=0x1437 NtUserGetDesktopID
@ stub -syscall=0x1438 NtUserGetDesktopVisualTransform
@ stub -syscall=0x1439 NtUserGetDeviceChangeInfo
@ stub -syscall=0x143a NtUserGetDisplayAutoRotationPreferences
@ stub -syscall=0x143b NtUserGetDisplayAutoRotationPreferencesByProcessId
@ stdcall -syscall=0x143c NtUserGetDisplayConfigBufferSizes(long ptr ptr)
@ stdcall -syscall=0x10a8 NtUserGetDoubleClickTime()
@ stub -syscall=0x143d NtUserGetDpiForCurrentProcess
@ stdcall -syscall=0x143e NtUserGetDpiForMonitor(long long ptr ptr)
@ stub -syscall=0x143f NtUserGetDwmCursorShape
@ stub -syscall=0x1440 NtUserGetExtendedPointerDeviceProperty
@ stdcall -syscall=0x1037 NtUserGetForegroundWindow()
@ stdcall -syscall=0x10eb NtUserGetGUIThreadInfo(long ptr)
@ stub -syscall=0x1441 NtUserGetGestureConfig
@ stub -syscall=0x1442 NtUserGetGestureExtArgs
@ stub -syscall=0x1443 NtUserGetGestureInfo
@ stub -syscall=0x1444 NtUserGetGuiResources
@ stub -syscall=0x1445 NtUserGetHDevName
@ stub -syscall=0x1446 NtUserGetHimetricScaleFactorFromPixelLocation
@ stub -syscall=0x1447 NtUserGetIMEShowStatus
@ stdcall -syscall=0x104a NtUserGetIconInfo(long ptr ptr ptr ptr long)
@ stdcall -syscall=0x1080 NtUserGetIconSize(long long ptr ptr)
@ stub -syscall=0x1448 NtUserGetImeHotKey
@ stub -syscall=0x1449 NtUserGetImeInfoEx
@ stub -syscall=0x144a NtUserGetInputContainerId
@ stub -syscall=0x144b NtUserGetInputDesktop
@ stub -syscall=0x144c NtUserGetInputEvent
@ stub -syscall=0x144d NtUserGetInputLocaleInfo
@ stub -syscall=0x144e NtUserGetInteractiveControlDeviceInfo
@ stub -syscall=0x144f NtUserGetInteractiveControlInfo
@ stub -syscall=0x1450 NtUserGetInteractiveCtrlSupportedWaveforms
@ stdcall -syscall NtUserGetInternalWindowPos(long ptr ptr)
@ stdcall -syscall=0x1451 NtUserGetKeyNameText(long ptr long)
@ stdcall -syscall=0x1002 NtUserGetKeyState(long)
@ stdcall -syscall=0x1453 NtUserGetKeyboardLayout(long)
@ stdcall -syscall=0x1053 NtUserGetKeyboardLayoutList(long ptr)
@ stdcall -syscall=0x1454 NtUserGetKeyboardLayoutName(ptr)
@ stdcall -syscall=0x1071 NtUserGetKeyboardState(ptr)
@ stub -syscall=0x1455 NtUserGetKeyboardType
@ stdcall -syscall=0x1457 NtUserGetLayeredWindowAttributes(long ptr ptr ptr)
@ stub -syscall=0x1458 NtUserGetListBoxInfo
@ stdcall -syscall=0x10b3 NtUserGetMenuBarInfo(long long long ptr)
@ stub -syscall=0x1459 NtUserGetMenuIndex
@ stdcall -syscall=0x145a NtUserGetMenuItemRect(long long long ptr)
@ stdcall -syscall=0x1004 NtUserGetMessage(ptr long long long)
@ stub -syscall=0x145b NtUserGetMessagePos
@ stub -syscall=0x145c NtUserGetMinuserIdForBaseWindow
@ stub -syscall=0x145d NtUserGetModernAppWindow
@ stdcall -syscall=0x145e NtUserGetMouseMovePointsEx(long ptr ptr long long)
@ stdcall -syscall=0x1065 NtUserGetObjectInformation(long long long long ptr)
@ stub -syscall=0x145f NtUserGetOemBitmapSize
@ stdcall -syscall=0x10c5 NtUserGetOpenClipboardWindow()
@ stub -syscall=0x1334 NtUserGetOwnerTransformedMonitorRect
@ stub -syscall=0x1460 NtUserGetPhysicalDeviceRect
@ stub -syscall=0x1461 NtUserGetPointerCursorId
@ stub -syscall=0x1462 NtUserGetPointerDevice
@ stub -syscall=0x1463 NtUserGetPointerDeviceCursors
@ stub -syscall=0x1464 NtUserGetPointerDeviceInputSpace
@ stub -syscall=0x1465 NtUserGetPointerDeviceOrientation
@ stub -syscall=0x1466 NtUserGetPointerDeviceProperties
@ stub -syscall=0x1467 NtUserGetPointerDeviceRects
@ stub -syscall=0x1468 NtUserGetPointerDevices
@ stub -syscall=0x1469 NtUserGetPointerFrameTimes
@ stdcall -syscall=0x146b NtUserGetPointerInfoList(long long long long long ptr ptr ptr)
@ stub -syscall=0x146c NtUserGetPointerInputTransform
@ stub -syscall=0x146d NtUserGetPointerProprietaryId
@ stub -syscall=0x146e NtUserGetPointerType
@ stub -syscall NtUserGetPrecisionTouchPadConfiguration
@ stdcall -syscall=0x146f NtUserGetPriorityClipboardFormat(ptr long)
@ stdcall -syscall=0x1470 NtUserGetProcessDefaultLayout(ptr)
@ stdcall -syscall=0x1471 NtUserGetProcessDpiAwarenessContext(long)
@ stub -syscall=0x1472 NtUserGetProcessUIContextInformation
@ stdcall -syscall=0x101f NtUserGetProcessWindowStation()
@ stdcall -syscall=0x100c NtUserGetProp(long wstr)
@ stub -syscall=0x1473 NtUserGetProp2
@ stub -syscall=0x1474 NtUserGetQueueIocp
@ stdcall -syscall=0x1475 NtUserGetQueueStatus(long)
@ stub -syscall=0x1476 NtUserGetQueueStatusReadonly
@ stdcall -syscall=0x1477 NtUserGetRawInputBuffer(ptr ptr long)
@ stdcall -syscall=0x1478 NtUserGetRawInputData(ptr long ptr ptr long)
@ stdcall -syscall=0x1479 NtUserGetRawInputDeviceInfo(ptr long ptr ptr)
@ stdcall -syscall=0x147a NtUserGetRawInputDeviceList(ptr ptr long)
@ stub -syscall=0x147b NtUserGetRawPointerDeviceData
@ stdcall -syscall=0x147c NtUserGetRegisteredRawInputDevices(ptr ptr long)
@ stub -syscall=0x147d NtUserGetRequiredCursorSizes
@ stub -syscall=0x147e NtUserGetResizeDCompositionSynchronizationObject
@ stdcall -syscall=0x108b NtUserGetScrollBarInfo(long long ptr)
@ stub -syscall=0x147f NtUserGetSendMessageReceiver
@ stub -syscall=0x1480 NtUserGetSharedWindowData
@ stub -syscall NtUserGetSuppressedWindowActions
@ stub -syscall=0x1481 NtUserGetSysMenuOffset
@ stub -syscall=0x1482 NtUserGetSystemContentRects
@ stdcall -syscall=0x1483 NtUserGetSystemDpiForProcess(long)
@ stdcall -syscall=0x105b NtUserGetSystemMenu(long long)
@ stdcall -syscall=0x107b NtUserGetThreadDesktop(long)
@ stdcall -syscall=0x1000 NtUserGetThreadState(long)
@ stdcall -syscall=0x1087 NtUserGetTitleBarInfo(long ptr)
@ stub -syscall=0x1484 NtUserGetTopLevelWindow
@ stdcall -syscall=0x1485 NtUserGetTouchInputInfo(ptr long ptr long)
@ stub -syscall=0x1486 NtUserGetTouchValidationStatus
@ stub -syscall=0x1487 NtUserGetUniformSpaceMapping
@ stub -syscall=0x1488 NtUserGetUnpredictedMessagePos
@ stdcall -syscall=0x104e NtUserGetUpdateRect(long ptr long)
@ stdcall -syscall=0x107e NtUserGetUpdateRgn(long long long)
@ stdcall -syscall=0x1489 NtUserGetUpdatedClipboardFormats(ptr long ptr)
@ stub -syscall=0x148a NtUserGetWOWClass
@ stub -syscall=0x148b NtUserGetWinStationInfo
@ stub -syscall=0x148c NtUserGetWindowBand
@ stub -syscall=0x148d NtUserGetWindowCompositionAttribute
@ stub -syscall=0x148e NtUserGetWindowCompositionInfo
@ stdcall -syscall=0x148f NtUserGetWindowContextHelpId(long)
@ stdcall -syscall=0x105e NtUserGetWindowDC(long)
@ stdcall -syscall=0x1490 NtUserGetWindowDisplayAffinity(ptr ptr)
@ stub -syscall=0x1491 NtUserGetWindowFeedbackSetting
@ stub -syscall NtUserGetWindowGroupId
@ stub -syscall=0x1492 NtUserGetWindowMinimizeRect
@ stdcall -syscall=0x10c2 NtUserGetWindowPlacement(long ptr)
@ stub -syscall=0x1493 NtUserGetWindowProcessHandle
@ stdcall -syscall=0x1494 NtUserGetWindowRgnEx(long long long)
@ stub -syscall=0x1495 NtUserGetWindowThreadProcessId
@ stub -syscall=0x1496 NtUserGetWindowTrackInfoAsync
@ stub -syscall=0x1497 NtUserGhostWindowFromHungWindow
@ stub -syscall=0x1499 NtUserHandleDelegatedInput
@ stub -syscall=0x149a NtUserHandleSystemThreadCreationFailure
@ stub -syscall=0x149b NtUserHardErrorControl
@ stdcall -syscall=0x101d NtUserHideCaret(long)
@ stub -syscall=0x149c NtUserHideCursorNoCapture
@ stub -syscall=0x149d NtUserHidePointerContactVisualization
@ stdcall -syscall=0x149e NtUserHiliteMenuItem(long long long long)
@ stub -syscall=0x149f NtUserHungWindowFromGhostWindow
@ stub -syscall=0x14a0 NtUserHwndQueryRedirectionInfo
@ stub -syscall=0x14a1 NtUserHwndSetRedirectionInfo
@ stub -syscall=0x14a2 NtUserImpersonateDdeClientWindow
@ stub -syscall=0x14a3 NtUserInheritWindowMonitor
@ stub -syscall=0x14a4 NtUserInitAnsiOem
@ stub -syscall NtUserInitTask
@ stub -syscall=0x14a5 NtUserInitThreadCoreMessagingIocp
@ stub -syscall=0x14a6 NtUserInitThreadCoreMessagingIocp2
@ stub -syscall=0x14a7 NtUserInitialize
@ stdcall -syscall=0x14a8 NtUserInitializeClientPfnArrays(ptr ptr ptr ptr)
@ stub -syscall=0x14a9 NtUserInitializeGenericHidInjection
@ stub -syscall=0x14aa NtUserInitializeInputDeviceInjection
@ stub -syscall NtUserInitializePointerDeviceInjection
@ stub -syscall NtUserInitializePointerDeviceInjectionEx
@ stub -syscall=0x14ab NtUserInitializeTouchInjection
@ stub -syscall=0x14ad NtUserInjectDeviceInput
@ stub -syscall=0x14ae NtUserInjectGenericHidInput
@ stub -syscall=0x14af NtUserInjectGesture
@ stub -syscall=0x14b0 NtUserInjectKeyboardInput
@ stub -syscall=0x14b1 NtUserInjectMouseInput
@ stub -syscall=0x14b2 NtUserInjectPointerInput
@ stub -syscall=0x14b3 NtUserInjectTouchInput
@ stub -syscall=0x14b5 NtUserInteractiveControlQueryUsage
@ stdcall -syscall=0x14b6 NtUserInternalGetWindowIcon(ptr long)
@ stdcall -syscall=0x105d NtUserInternalGetWindowText(long ptr long)
@ stub -syscall NtUserInternalStartMoveSize
@ stub -syscall=0x14b7 NtUserInternalToUnicode
@ stdcall -syscall=0x1003 NtUserInvalidateRect(long ptr long)
@ stdcall -syscall=0x10b6 NtUserInvalidateRgn(long long long)
@ stdcall -syscall=0x14b8 NtUserIsChildWindowDpiMessageEnabled(ptr)
@ stdcall -syscall=0x102a NtUserIsClipboardFormatAvailable(long)
@ stdcall -syscall=0x14ba NtUserIsMouseInPointerEnabled()
@ stub -syscall=0x14bb NtUserIsMouseInputEnabled
@ stub -syscall=0x14bc NtUserIsNonClientDpiScalingEnabled
@ stub -syscall NtUserIsQueueAttached
@ stub -syscall=0x14bd NtUserIsResizeLayoutSynchronizationEnabled
@ stub -syscall=0x14be NtUserIsTopLevelWindow
@ stdcall -syscall=0x14bf NtUserIsTouchWindow(long ptr)
@ stub -syscall=0x14c0 NtUserIsWindowBroadcastingDpiToChildren
@ stub -syscall=0x14c1 NtUserIsWindowDisplayChangeSuppressed
@ stub -syscall=0x14c2 NtUserIsWindowGDIScaledDpiMessageEnabled
@ stdcall -syscall=0x14c3 NtUserKillSystemTimer(long long)
@ stdcall -syscall=0x1019 NtUserKillTimer(long long)
@ stub -syscall=0x14c4 NtUserLW_LoadFonts
@ stub -syscall=0x14c5 NtUserLayoutCompleted
@ stub -syscall=0x14c6 NtUserLinkDpiCursor
@ stub -syscall=0x14c7 NtUserLoadCursorsAndIcons
@ stub -syscall=0x14c8 NtUserLoadKeyboardLayoutEx
@ stub -syscall=0x14c9 NtUserLoadUserApiHook
@ stub -syscall=0x14ca NtUserLockCursor
@ stub -syscall=0x14cb NtUserLockSetForegroundWindow
@ stub -syscall=0x14cc NtUserLockWindowStation
@ stdcall -syscall=0x10f2 NtUserLockWindowUpdate(long)
@ stub -syscall=0x14cd NtUserLockWorkStation
@ stdcall -syscall=0x14ce NtUserLogicalToPerMonitorDPIPhysicalPoint(long ptr)
@ stub -syscall=0x14cf NtUserLogicalToPhysicalDpiPointForWindow
@ stub -syscall=0x14d0 NtUserLogicalToPhysicalPoint
@ stub -syscall=0x14d1 NtUserMNDragLeave
@ stub -syscall=0x14d2 NtUserMNDragOver
@ stub -syscall=0x14d3 NtUserMagControl
@ stub -syscall=0x14d4 NtUserMagGetContextInformation
@ stub -syscall=0x14d5 NtUserMagSetContextInformation
@ stub -syscall=0x14d6 NtUserMapDesktopObject
@ stub -syscall=0x14d7 NtUserMapPointsByVisualIdentifier
@ stdcall -syscall=0x1055 NtUserMapVirtualKeyEx(long long long)
@ stub -syscall=0x14d8 NtUserMarkWindowForRawMouse
@ stdcall -syscall=0x14d9 NtUserMenuItemFromPoint(long long long long)
@ stdcall -syscall=0x14da NtUserMessageBeep(long)
@ stdcall -syscall=0x1005 NtUserMessageCall(long long long long long long long)
@ stub -syscall=0x14db NtUserMinInitialize
@ stub -syscall=0x14dc NtUserMinMaximize
@ stdcall -syscall=0x10f9 NtUserModifyUserStartupInfoFlags(long long)
@ stub -syscall=0x14dd NtUserModifyWindowTouchCapability
@ stdcall -syscall=0x1058 NtUserMoveWindow(long long long long long long)
@ stdcall -syscall=0x14de NtUserMsgWaitForMultipleObjectsEx(long ptr long long long)
@ stub -syscall=0x14df NtUserNavigateFocus
@ stub -syscall=0x14e0 NtUserNlsKbdSendIMENotification
@ stdcall -syscall=0x14e1 NtUserNotifyIMEStatus(long long)
@ stub -syscall=0x14e2 NtUserNotifyOverlayWindow
@ stub -syscall=0x1085 NtUserNotifyProcessCreate
@ stdcall -syscall=0x1028 NtUserNotifyWinEvent(long long long long)
@ stdcall -syscall=0x10bd NtUserOpenClipboard(long long)
@ stdcall -syscall=0x109a NtUserOpenDesktop(ptr long long)
@ stdcall -syscall=0x14e3 NtUserOpenInputDesktop(long long long)
@ stub -syscall=0x14e4 NtUserOpenThreadDesktop
@ stdcall -syscall=0x1097 NtUserOpenWindowStation(ptr long)
@ stub -syscall=0x1100 NtUserPaintDesktop
@ stub -syscall=0x10db NtUserPaintMenuBar
@ stub -syscall=0x14e5 NtUserPaintMonitor
@ stdcall -syscall=0x1001 NtUserPeekMessage(ptr long long long long)
@ stdcall -syscall=0x14e6 NtUserPerMonitorDPIPhysicalToLogicalPoint(long ptr)
@ stub -syscall=0x14e7 NtUserPhysicalToLogicalDpiPointForWindow
@ stub -syscall=0x14e8 NtUserPhysicalToLogicalPoint
@ stub -syscall=0x14e9 NtUserPlayEventSound
@ stub -syscall=0x14ea NtUserPostKeyboardInputMessage
@ stdcall -syscall=0x100d NtUserPostMessage(long long long long)
@ stdcall -syscall=0x14eb NtUserPostQuitMessage(long)
@ stdcall -syscall=0x1059 NtUserPostThreadMessage(long long long long)
@ stub -syscall=0x14ec NtUserPrepareForLogoff
@ stdcall -syscall=0x14ed NtUserPrintWindow(long long long)
@ stub -syscall=0x10e2 NtUserProcessConnect
@ stub -syscall=0x14ee NtUserProcessInkFeedbackCommand
@ stub -syscall=0x14ef NtUserPromoteMouseInPointer
@ stub -syscall=0x14f0 NtUserPromotePointer
@ stub -syscall NtUserQueryActivationObject
@ stub -syscall=0x14f1 NtUserQueryBSDRWindow
@ stdcall -syscall=0x14f2 NtUserQueryDisplayConfig(long ptr ptr ptr ptr ptr)
@ stub -syscall=0x14f3 NtUserQueryInformationThread
@ stdcall -syscall=0x14f4 NtUserQueryInputContext(long long)
@ stub -syscall=0x14f5 NtUserQuerySendMessage
@ stdcall -syscall=0x100e NtUserQueryWindow(long long)
@ stub -syscall=0x14f6 NtUserRaiseLowerShellWindow
@ stdcall -syscall=0x14f7 NtUserRealChildWindowFromPoint(long long long)
@ stub -syscall=0x10d7 NtUserRealInternalGetMessage
@ stub -syscall=0x14f8 NtUserRealWaitMessageEx
@ stdcall -syscall=0x14f9 NtUserRealizePalette(long)
@ stub -syscall=0x14fa NtUserReassociateQueueEventCompletionPacket
@ stub -syscall=0x14fb NtUserRedrawFrame
@ stub -syscall=0x14fc NtUserRedrawFrameAndHook
@ stub -syscall=0x14fd NtUserRedrawTitle
@ stdcall -syscall=0x1011 NtUserRedrawWindow(long ptr long long)
@ stub -syscall=0x14fe NtUserRegisterBSDRWindow
@ stdcall -syscall=0x10a2 NtUserRegisterClassExWOW(ptr ptr ptr ptr long long long)
@ stub -syscall=0x14ff NtUserRegisterCloakedNotification
@ stub -syscall=0x1501 NtUserRegisterDManipHook
@ stub -syscall=0x1502 NtUserRegisterEdgy
@ stub -syscall=0x1503 NtUserRegisterErrorReportingDialog
@ stub -syscall=0x1504 NtUserRegisterForCustomDockTargets
@ stub -syscall=0x1505 NtUserRegisterForTooltipDismissNotification
@ stub -syscall=0x1506 NtUserRegisterGhostWindow
@ stdcall -syscall=0x1507 NtUserRegisterHotKey(long long long long)
@ stub -syscall=0x1508 NtUserRegisterLPK
@ stub -syscall=0x1509 NtUserRegisterLogonProcess
@ stub -syscall=0x150a NtUserRegisterManipulationThread
@ stub -syscall=0x150b NtUserRegisterPointerDeviceNotifications
@ stub -syscall=0x150c NtUserRegisterPointerInputTarget
@ stub -syscall NtUserRegisterPrecisionTouchpadWindow
@ stdcall -syscall=0x150d NtUserRegisterRawInputDevices(ptr long long)
@ stub -syscall=0x150e NtUserRegisterServicesProcess
@ stub -syscall=0x150f NtUserRegisterSessionPort
@ stub -syscall=0x1510 NtUserRegisterShellHookWindow
@ stub -syscall NtUserRegisterShellPTPListener
@ stub -syscall=0x1511 NtUserRegisterSiblingFrostWindow
@ stub -syscall=0x1512 NtUserRegisterSystemThread
@ stub -syscall=0x1513 NtUserRegisterTasklist
@ stub -syscall=0x1514 NtUserRegisterTouchHitTestingWindow
@ stdcall -syscall=0x1515 NtUserRegisterTouchPadCapable(long)
@ stub -syscall=0x1517 NtUserRegisterUserApiHook
@ stub -syscall NtUserRegisterUserHungAppHandlers
@ stub -syscall=0x1518 NtUserRegisterWindowArrangementCallout
@ stdcall -syscall=0x1032 NtUserRegisterWindowMessage(ptr)
@ stdcall -syscall=0x1519 NtUserReleaseCapture()
@ stdcall -syscall=0x151a NtUserReleaseDC(long long)
@ stub -syscall=0x151b NtUserReleaseDwmHitTestWaiters
@ stub -syscall=0x151c NtUserRemoteConnect
@ stub -syscall=0x151d NtUserRemoteConnectState
@ stub -syscall=0x151e NtUserRemoteConsoleShadowStop
@ stub -syscall=0x151f NtUserRemoteDisconnect
@ stub -syscall=0x1520 NtUserRemoteNotify
@ stub -syscall=0x1521 NtUserRemotePassthruDisable
@ stub -syscall=0x1522 NtUserRemotePassthruEnable
@ stub -syscall=0x1523 NtUserRemoteReconnect
@ stub -syscall=0x1524 NtUserRemoteRedrawRectangle
@ stub -syscall=0x1525 NtUserRemoteRedrawScreen
@ stub -syscall=0x1526 NtUserRemoteShadowCleanup
@ stub -syscall=0x1527 NtUserRemoteShadowSetup
@ stub -syscall=0x1528 NtUserRemoteShadowStart
@ stub -syscall=0x1529 NtUserRemoteShadowStop
@ stub -syscall=0x152a NtUserRemoteStopScreenUpdates
@ stub -syscall=0x152b NtUserRemoteThinwireStats
@ stdcall -syscall=0x152c NtUserRemoveClipboardFormatListener(long)
@ stub -syscall=0x152d NtUserRemoveInjectionDevice
@ stdcall -syscall=0x10e6 NtUserRemoveMenu(long long long)
@ stdcall -syscall=0x1041 NtUserRemoveProp(long wstr)
@ stub -syscall=0x152e NtUserRemoveQueueCompletion
@ stub -syscall=0x152f NtUserRemoveVisualIdentifier
@ stdcall -syscall=0x1530 NtUserReplyMessage(long)
@ stub -syscall=0x1531 NtUserReportInertia
@ stub -syscall NtUserRequestMoveSizeOperation
@ stub -syscall=0x1533 NtUserResetDblClk
@ stub -syscall=0x1534 NtUserResolveDesktopForWOW
@ stub -syscall=0x1535 NtUserRestoreWindowDpiChanges
@ stub -syscall=0x1049 NtUserSBGetParms
@ stub -syscall=0x1536 NtUserScaleSystemMetricForDPIWithoutCache
@ stdcall -syscall=0x1537 NtUserScheduleDispatchNotification(ptr)
@ stdcall -syscall=0x1064 NtUserScrollDC(long long long ptr ptr long ptr)
@ stdcall -syscall=0x10b0 NtUserScrollWindowEx(long long long ptr ptr long ptr long)
@ stdcall -syscall=0x101b NtUserSelectPalette(long long long)
@ stub -syscall=0x1538 NtUserSendEventMessage
@ stdcall -syscall=0x107a NtUserSendInput(long ptr long)
@ stub -syscall=0x1539 NtUserSendInteractiveControlHapticsReport
@ stub -syscall=0x153a NtUserSetActivationFilter
@ stub -syscall=0x153b NtUserSetActiveProcessForMonitor
@ stdcall -syscall=0x10cd NtUserSetActiveWindow(long)
@ stdcall -syscall=0x153c NtUserSetAdditionalForegroundBoostProcesses(ptr long ptr)
@ stub -syscall=0x153e NtUserSetAppImeLevel
@ stub -syscall=0x153f NtUserSetAutoRotation
@ stub -syscall=0x1540 NtUserSetBridgeWindowChild
@ stub -syscall=0x1541 NtUserSetBrokeredForeground
@ stub -syscall=0x1542 NtUserSetCalibrationData
@ stub -syscall=0x1543 NtUserSetCancelRotationDelayHintWindow
@ stdcall -syscall=0x1044 NtUserSetCapture(long)
@ stdcall -syscall=0x1544 NtUserSetCaretBlinkTime(long)
@ stdcall -syscall=0x1545 NtUserSetCaretPos(long long)
@ stub -syscall=0x1546 NtUserSetChildWindowNoActivate
@ stdcall -syscall=0x10b2 NtUserSetClassLong(long long long long)
@ stdcall -syscall=0x15d7 NtUserSetClassLongPtr(long long long long)
@ stdcall -syscall=0x1547 NtUserSetClassWord(long long long)
@ stdcall -syscall=0x10be NtUserSetClipboardData(long ptr ptr)
@ stdcall -syscall=0x1105 NtUserSetClipboardViewer(long)
@ stub -syscall=0x1548 NtUserSetCoreWindow
@ stub -syscall=0x1549 NtUserSetCoreWindowPartner
@ stub -syscall=0x154a NtUserSetCoveredWindowStates
@ stdcall -syscall=0x1018 NtUserSetCursor(long)
@ stub -syscall NtUserSetCursorContents
@ stdcall -syscall=0x1098 NtUserSetCursorIconData(long ptr ptr ptr)
@ stub -syscall=0x154b NtUserSetCursorIconDataEx
@ stdcall -syscall=0x154c NtUserSetCursorPos(long long)
@ stub -syscall=0x154d NtUserSetDesktopColorTransform
@ stub -syscall=0x154e NtUserSetDesktopVisualInputSink
@ stub -syscall=0x154f NtUserSetDialogControlDpiChangeBehavior
@ stub -syscall=0x1550 NtUserSetDialogPointer
@ stub -syscall=0x1551 NtUserSetDialogSystemMenu
@ stub -syscall=0x1552 NtUserSetDisplayAutoRotationPreferences
@ stub -syscall=0x1553 NtUserSetDisplayConfig
@ stub -syscall=0x1554 NtUserSetDisplayMapping
@ stub -syscall=0x1555 NtUserSetDoubleClickTime
@ stub -syscall=0x1556 NtUserSetDpiForWindow
@ stub -syscall NtUserSetFallbackForeground
@ stub -syscall=0x1557 NtUserSetFeatureReportResponse
@ stdcall -syscall=0x104c NtUserSetFocus(long)
@ stub -syscall=0x1558 NtUserSetForegroundRedirectionForActivationObject
@ stdcall -syscall=0x1559 NtUserSetForegroundWindow(long)
@ stub -syscall=0x155a NtUserSetForegroundWindowForApplication
@ stub -syscall=0x155b NtUserSetFullscreenMagnifierOffsetsDWMUpdated
@ stub -syscall=0x155d NtUserSetGestureConfig
@ stub -syscall=0x155e NtUserSetImeHotKey
@ stub -syscall=0x155f NtUserSetImeInfoEx
@ stub -syscall=0x1560 NtUserSetImeOwnerWindow
@ stub -syscall=0x10ce NtUserSetInformationThread
@ stub -syscall=0x1561 NtUserSetInputServiceState
@ stub -syscall=0x1562 NtUserSetInteractiveControlFocus
@ stub -syscall=0x1563 NtUserSetInteractiveCtrlRotationAngle
@ stdcall -syscall=0x1564 NtUserSetInternalWindowPos(long long ptr ptr)
@ stdcall -syscall=0x10dc NtUserSetKeyboardState(ptr)
@ stdcall -syscall=0x1566 NtUserSetLayeredWindowAttributes(ptr long long long)
@ stub -syscall=0x1567 NtUserSetMagnificationDesktopMagnifierOffsetsDWMUpdated
@ stub -syscall=0x1568 NtUserSetManipulationInputTarget
@ stdcall -syscall=0x156a NtUserSetMenu(long long)
@ stdcall -syscall=0x156b NtUserSetMenuContextHelpId(long long)
@ stdcall -syscall=0x10ee NtUserSetMenuDefaultItem(long long long)
@ stub -syscall=0x156c NtUserSetMenuFlagRtoL
@ stub -syscall=0x156d NtUserSetMessageExtraInfo
@ stub -syscall=0x156e NtUserSetMirrorRendering
@ stub -syscall=0x156f NtUserSetModernAppWindow
@ stub -syscall=0x1570 NtUserSetMonitorWorkArea
@ stub -syscall NtUserSetMouseInputRateLimitingTimer
@ stub -syscall=0x1571 NtUserSetMsgBox
@ stdcall -syscall=0x1572 NtUserSetObjectInformation(long long ptr long)
@ stdcall -syscall=0x1070 NtUserSetParent(long long)
@ stub -syscall NtUserSetPrecisionTouchPadConfiguration
@ stdcall -syscall=0x1573 NtUserSetProcessDefaultLayout(long)
@ stdcall -syscall=0x1574 NtUserSetProcessDpiAwarenessContext(long long)
@ stub -syscall=0x1575 NtUserSetProcessInteractionFlags
@ stub -syscall=0x1576 NtUserSetProcessLaunchForegroundPolicy
@ stub -syscall=0x1577 NtUserSetProcessMousewheelRoutingMode
@ stub -syscall=0x1578 NtUserSetProcessRestrictionExemption
@ stub -syscall=0x1579 NtUserSetProcessUIAccessZorder
@ stdcall -syscall=0x109b NtUserSetProcessWindowStation(long)
@ stdcall -syscall=0x157b NtUserSetProgmanWindow(long)
@ stdcall -syscall=0x1047 NtUserSetProp(long wstr ptr)
@ stub -syscall=0x157c NtUserSetProp2
@ stdcall -syscall=0x102b NtUserSetScrollInfo(long long ptr long)
@ stub -syscall=0x1419 NtUserSetSensorPresence
@ stub -syscall=0x157d NtUserSetSharedWindowData
@ stub -syscall=0x157e NtUserSetShellChangeNotifyHWND
@ stdcall -syscall=0x1580 NtUserSetShellWindowEx(long long)
@ stdcall -syscall=0x1581 NtUserSetSysColors(long ptr ptr)
@ stub -syscall=0x1582 NtUserSetSysMenu
@ stub -syscall=0x1583 NtUserSetSystemContentRects
@ stub -syscall=0x1584 NtUserSetSystemCursor
@ stdcall -syscall=0x10f3 NtUserSetSystemMenu(long long)
@ stdcall -syscall=0x1585 NtUserSetSystemTimer(long long long)
@ stub -syscall=0x1586 NtUserSetTSFEventState
@ stub -syscall=0x1587 NtUserSetTargetForResourceBrokering
@ stdcall -syscall=0x1588 NtUserSetTaskmanWindow(long)
@ stdcall -syscall=0x1089 NtUserSetThreadDesktop(long)
@ stub -syscall=0x1589 NtUserSetThreadInputBlocked
@ stub -syscall=0x158a NtUserSetThreadLayoutHandles
@ stub -syscall=0x158b NtUserSetThreadQueueMergeSetting
@ stub -syscall=0x10c6 NtUserSetThreadState
@ stdcall -syscall=0x1016 NtUserSetTimer(long long long ptr long)
@ stub -syscall=0x158c NtUserSetUserObjectCapability
@ stub -syscall=0x158d NtUserSetVisible
@ stub -syscall=0x158e NtUserSetWaitForQueueAttach
@ stub -syscall=0x158f NtUserSetWatermarkStrings
@ stdcall -syscall=0x10f0 NtUserSetWinEventHook(long long long ptr ptr long long long)
@ stub -syscall NtUserSetWindowArrangement
@ stub -syscall=0x1590 NtUserSetWindowBand
@ stub -syscall=0x1591 NtUserSetWindowCompositionAttribute
@ stub -syscall=0x1592 NtUserSetWindowCompositionTransition
@ stdcall -syscall=0x1593 NtUserSetWindowContextHelpId(long long)
@ stub -syscall=0x1594 NtUserSetWindowDisplayAffinity
@ stub -syscall=0x108d NtUserSetWindowFNID
@ stub -syscall=0x1595 NtUserSetWindowFeedbackSetting
@ stub -syscall NtUserSetWindowGroup
@ stdcall -syscall=0x1056 NtUserSetWindowLong(long long long long)
@ stdcall -syscall=0x15d8 NtUserSetWindowLongPtr(long long long long)
@ stub -syscall=0x1596 NtUserSetWindowMessageCapability
@ stdcall -syscall=0x10cf NtUserSetWindowPlacement(long ptr)
@ stdcall -syscall=0x1021 NtUserSetWindowPos(long long long long long long long)
@ stdcall -syscall=0x10b8 NtUserSetWindowRgn(long long long)
@ stub -syscall=0x1597 NtUserSetWindowRgnEx
@ stub -syscall=0x1598 NtUserSetWindowShowState
@ stub -syscall=0x1599 NtUserSetWindowState
@ stub -syscall=0x159a NtUserSetWindowStationUser
@ stdcall -syscall=0x10d5 NtUserSetWindowWord(long long long)
@ stub -syscall=0x10ed NtUserSetWindowsHookAW
@ stdcall -syscall=0x1084 NtUserSetWindowsHookEx(ptr ptr long long ptr long)
@ stub -syscall=0x159b NtUserShellForegroundBoostProcess
@ stub -syscall=0x159c NtUserShellHandwritingDelegateInput
@ stub -syscall=0x159d NtUserShellHandwritingHandleDelegatedInput
@ stub -syscall=0x159e NtUserShellHandwritingUndelegateInput
@ stub -syscall=0x159f NtUserShellMigrateWindow
@ stub -syscall=0x15a0 NtUserShellRegisterHotKey
@ stub -syscall=0x15a1 NtUserShellSetWindowPos
@ stdcall -syscall=0x1022 NtUserShowCaret(long)
@ stdcall -syscall=0x15a2 NtUserShowCursor(long)
@ stdcall -syscall=0x15a3 NtUserShowOwnedPopups(long long)
@ stdcall -syscall=0x1038 NtUserShowScrollBar(long long long)
@ stub -syscall=0x15a4 NtUserShowStartGlass
@ stub -syscall=0x15a5 NtUserShowSystemCursor
@ stdcall -syscall=0x1052 NtUserShowWindow(long long)
@ stdcall -syscall=0x1106 NtUserShowWindowAsync(long long)
@ stub -syscall=0x15a6 NtUserShutdownBlockReasonCreate
@ stub -syscall=0x15a7 NtUserShutdownBlockReasonQuery
@ stub -syscall=0x15a8 NtUserShutdownReasonDestroy
@ stub -syscall=0x15a9 NtUserSignalRedirectionStartComplete
@ stub -syscall=0x15aa NtUserSlicerControl
@ stub -syscall=0x15ab NtUserSoundSentry
@ stub -syscall=0x15ac NtUserStopAndEndInertia
@ stub -syscall NtUserSuppressWindowActions
@ stub -syscall=0x15ad NtUserSuppressWindowDisplayChange
@ stub -syscall=0x15ae NtUserSwapMouseButton
@ stdcall -syscall=0x15af NtUserSwitchDesktop(long)
@ stub -syscall=0x15b0 NtUserSwitchToThisWindow
@ stdcall -syscall=0x103d NtUserSystemParametersInfo(long long ptr long)
@ stdcall -syscall=0x15b1 NtUserSystemParametersInfoForDpi(long long ptr long long)
@ stub -syscall=0x15b2 NtUserTestForInteractiveUser
@ stub -syscall=0x15b3 NtUserThreadMessageQueueAttached
@ stdcall -syscall=0x10f4 NtUserThunkedMenuInfo(long ptr)
@ stdcall -syscall=0x1090 NtUserThunkedMenuItemInfo(long long long long ptr ptr)
@ stdcall -syscall=0x1072 NtUserToUnicodeEx(long long ptr ptr long long long)
@ stub -syscall=0x15b4 NtUserTraceLoggingSendMixedModeTelemetry
@ stdcall -syscall=0x10c8 NtUserTrackMouseEvent(ptr)
@ stdcall -syscall=0x15b5 NtUserTrackPopupMenuEx(long long long long long ptr)
@ stub -syscall=0x15b6 NtUserTransformPoint
@ stub -syscall=0x15b7 NtUserTransformRect
@ stdcall -syscall=0x100f NtUserTranslateAccelerator(long long ptr)
@ stdcall -syscall=0x100b NtUserTranslateMessage(ptr long)
@ stub -syscall=0x15b8 NtUserUndelegateInput
@ stdcall -syscall=0x10f1 NtUserUnhookWinEvent(long)
@ stdcall -syscall=0x15b9 NtUserUnhookWindowsHook(long ptr)
@ stdcall -syscall=0x1069 NtUserUnhookWindowsHookEx(long)
@ stub -syscall=0x15ba NtUserUnloadKeyboardLayout
@ stub -syscall=0x15bb NtUserUnlockWindowStation
@ stdcall -syscall=0x10ad NtUserUnregisterClass(ptr ptr ptr)
@ stdcall -syscall=0x15bc NtUserUnregisterHotKey(long long)
@ stub -syscall=0x15bd NtUserUnregisterSessionPort
@ stub -syscall=0x15be NtUserUnregisterUserApiHook
@ stub -syscall=0x15bf NtUserUpdateClientRect
@ stub -syscall=0x15c0 NtUserUpdateDefaultDesktopThumbnail
@ stdcall -syscall=0x15c1 NtUserUpdateInputContext(long long ptr)
@ stub -syscall=0x15c2 NtUserUpdateInstance
@ stdcall -syscall=0x15c3 NtUserUpdateLayeredWindow(long long ptr ptr long ptr long ptr long ptr)
@ stub -syscall=0x15c4 NtUserUpdatePerUserImmEnabling
@ stub -syscall=0x15c5 NtUserUpdatePerUserSystemParameters
@ stub -syscall=0x15c6 NtUserUpdateWindow
@ stub -syscall=0x15c7 NtUserUpdateWindowInputSinkHints
@ stub -syscall=0x15c8 NtUserUpdateWindowTrackingInfo
@ stub -syscall=0x15c9 NtUserUpdateWindows
@ stub -syscall=0x15ca NtUserUserHandleGrantAccess
@ stub -syscall=0x15cb NtUserUserPowerCalloutWorker
@ stub -syscall=0x15cc NtUserValidateHandleSecure
@ stdcall -syscall=0x10bb NtUserValidateRect(long ptr)
@ stdcall -syscall=0x15cd NtUserValidateRgn(long long)
@ stub -syscall=0x1014 NtUserValidateTimerCallback
@ stdcall -syscall=0x1024 NtUserVkKeyScanEx(long long)
@ stub -syscall NtUserWOWCleanup
@ stub -syscall NtUserWOWModuleUnload
@ stub -syscall=0x15ce NtUserWaitAvailableMessageEx
@ stdcall -syscall=0x15cf NtUserWaitForInputIdle(long long long)
@ stub -syscall NtUserWaitForMsgAndEvent
@ stub -syscall=0x15d0 NtUserWaitForRedirectionStartComplete
@ stdcall -syscall=0x100a NtUserWaitMessage()
@ stub -syscall=0x15d1 NtUserWakeRITForShutdown
@ stdcall -syscall=0x15d2 NtUserWindowFromDC(long)
@ stub -syscall=0x15d3 NtUserWindowFromPhysicalPoint
@ stdcall -syscall=0x1012 NtUserWindowFromPoint(long long)
@ stub -syscall NtUserYieldTask
@ stub -syscall=0x15d4 NtUserZapActiveAndFocus
@ stub -syscall=0x15d5 NtValidateCompositionSurfaceHandle
@ stub -syscall=0x15d6 NtVisualCaptureBits
# extern gDispatchTableValues
