#!/usr/bin/env python3
# TuxBlox - Linux Compatibility Layer for the Roblox Engine
# Copyright (C) 2026 TuxBlox Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Turns the files directly in a data folder into one C++ header, so the
# launcher carries its data inside the binary instead of reading it from disk.

import json
import sys
from pathlib import Path

Delimiter = "TUXBLOXDATA"

def loadFiles(dataDir):
    if not dataDir.is_dir():
        sys.exit(f"{dataDir}: not a folder, cannot load data files from it")
    files = []
    for path in sorted(dataDir.iterdir()):
        if not path.is_file():
            continue
        if '"' in path.name or "\\" in path.name:
            sys.exit(f"{path}: filename contains a quote or backslash, cannot embed")
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            sys.exit(f"{path}: not valid UTF-8 text, cannot embed binary content in a C++ raw string")
        if path.suffix == ".json":
            try:
                json.loads(text)
            except json.JSONDecodeError as failure:
                sys.exit(f"{path}: not valid JSON: {failure}")
        if f"){Delimiter}\"" in text:
            sys.exit(f"{path}: contains the raw string terminator, cannot embed")
        files.append((path.name, text))
    return files

def render(files):
    lines = [
        "// Generated by compat/tuxblox/tools/embed-data.py. Do not edit.",
        "",
        "#pragma once",
        "",
        "#include <map>",
        "#include <string>",
        "#include <string_view>",
        "",
        "namespace tuxblox_data {",
        "",
        "inline std::string_view find(const std::string &name) {",
        "    static const std::map<std::string, std::string_view> Files = {",
    ]
    for name, text in files:
        lines.append(f"        {{\"{name}\", R\"{Delimiter}({text}){Delimiter}\"}},")
    lines += [
        "    };",
        "    const auto match = Files.find(name);",
        "    return (match == Files.end()) ? std::string_view() : match->second;",
        "}",
        "",
        "} // namespace tuxblox_data",
        "",
    ]
    return "\n".join(lines)

def main():
    if len(sys.argv) != 3:
        sys.exit("usage: ./embed-data.py <data folder> <output header>")
    dataDir = Path(sys.argv[1])
    files = loadFiles(dataDir)
    if not files:
        sys.exit(f"{dataDir}: no data files found")
    Path(sys.argv[2]).write_text(render(files), encoding="utf-8")

main()
